rich-content-editor/src/RichContentEditor/RichContentEditor.jsx
Adds support for default keyboard shortcuts like CMD+B - bold.
[Full list](https://github.com/facebook/draft-js/blob/master/src/component/utils/getDefaultKeyBinding.js#L67)
=> Handle keyboard shortcuts

packages/common/src/Base/baseToolbarButton.jsx, packages/common/src/Base/buttons/BlockLinkButton.jsx, packages/common/src/Base/buttons/BlockLinkPanel.jsx, packages/common/src/Base/buttons/keys.js, packages/common/src/Base/createBaseToolbar.jsx, packages/common/src/Styles/plugin-toolbar.scss, packages/plugin-html/src/toolbar/inlineButtons.js
=> Add inline panel button to HTML plugin toolbar

packages/plugin-html/src/IframeHtml.jsx, packages/plugin-html/src/toolbar/HtmlEditPanel.jsx
- Rerender html iframe on prop change
- Update componentData only when submit is clicked
=> [html] fix(IframeHtml) Rerender html iframe

packages/editor/src/RichContentEditor/RichContentEditor.jsx, packages/editor/src/RichContentEditor/handleReturnCommand.js
=> handle softNewLine (shift+enter)

packages/common/package.json, packages/editor/package.json, packages/plugin-code-block/package.json, packages/plugin-divider/package.json, packages/plugin-emoji/package.json, packages/plugin-gallery/package.json, packages/plugin-hashtag/package.json, packages/plugin-html/package.json, packages/plugin-image/package.json, packages/plugin-link/package.json, packages/plugin-mentions/package.json, packages/plugin-video/package.json, packages/viewer/package.json, rollup.config.js
Reverts wix-incubator/rich-content#73
=> Revert "added commonjs bundle"

packages/common/src/Base/baseToolbarButton.jsx, packages/common/src/Base/createBaseInsertPluginButton.jsx, packages/plugin-gallery/src/components/gallery-settings-modal.js
Pass additional parameter (`componentData`) to `handleFileSelection` helper. This param needed for getting actual images of gallery/image.
=> Pass componentData to handleFileSelection

CHANGELOG.md, packages/common/src/Utils/normalizeInitialState.js
=> [common] fix(normalizeInitialState): normalize text for atomic blocks

examples/editor/.gitignore, examples/editor/package.json, examples/viewer/.gitignore, examples/viewer/package.json, scripts/customPublish.js, scripts/deployExamples.js
=> [examples] infra(surge auto deploy)

CHANGELOG.md, packages/common/src/Components/LinkPanel.jsx, packages/common/src/Components/TextInput.jsx, packages/common/src/Components/Tooltip.jsx
`Tooltip` performance: rebuilt on `shouldRebuildOnUpdate() === true`
=> Tooltip performance fix

CHANGELOG.md, packages/common/src/Base/baseToolbarButton.jsx, packages/common/src/Base/createBaseInsertPluginButton.jsx, packages/common/src/Utils/simplePubsub.js, packages/plugin-gallery/src/components/gallery-settings-modal.js, packages/plugin-gallery/src/gallery-component.jsx, packages/plugin-gallery/src/toolbar/inline-buttons.jsx, packages/plugin-image/src/image-component.jsx, packages/plugin-image/src/toolbar/inline-buttons.jsx
=> [*] fix(plugin handlers): use pubsub get/setBlockHandler methods

CHANGELOG.md, docs/ToolbarCustomization.md, examples/editor/src/PluginsConfig.js, packages/common/src/Base/createBasePlugin.jsx, packages/common/src/Base/createBaseToolbar.jsx, packages/common/src/Base/default-toolbar-settings.js, packages/common/src/consts.js, packages/editor/src/RichContentEditor/RichContentEditor.jsx, packages/editor/src/RichContentEditor/Toolbars/createEditorToolbars.js, packages/editor/src/RichContentEditor/createPlugins.jsx
=> Plugin toolbar customization

CHANGELOG.md, docs/ToolbarCustomization.md, examples/editor/src/PluginsConfig.js, packages/common/src/Base/createBaseToolbar.jsx, packages/common/src/Base/default-toolbar-settings.js, packages/common/src/Utils/mergeToolbarSettings.js, packages/common/src/consts.js, packages/common/src/index.js, packages/editor/src/RichContentEditor/RichContentEditor.jsx, packages/editor/src/RichContentEditor/Toolbars/InlineToolbar/InlineToolbar.jsx, packages/editor/src/RichContentEditor/Toolbars/InlineToolbar/createInlineTextToolbar.jsx, packages/editor/src/RichContentEditor/Toolbars/InlineToolbar/createInlineToolbar.jsx, packages/editor/src/RichContentEditor/Toolbars/SideToolbar/SideToolbar.jsx, packages/editor/src/RichContentEditor/Toolbars/SideToolbar/createSideToolbar.jsx, packages/editor/src/RichContentEditor/Toolbars/StaticToolbar/StaticToolbar.jsx, packages/editor/src/RichContentEditor/Toolbars/StaticToolbar/createFooterToolbar.jsx, packages/editor/src/RichContentEditor/Toolbars/StaticToolbar/createMobileToolbar.jsx, packages/editor/src/RichContentEditor/Toolbars/StaticToolbar/createStaticTextToolbar.jsx, packages/editor/src/RichContentEditor/Toolbars/StaticToolbar/createStaticToolbar.jsx, packages/editor/src/RichContentEditor/Toolbars/createEditorToolbars.js, packages/editor/src/RichContentEditor/Toolbars/default-toolbar-settings.js
=> Floating toolbar display mode

CHANGELOG.md, examples/editor/src/PluginsConfig.js, packages/plugin-mentions/src/createMentionsPlugin.js, packages/plugin-mentions/src/positionSuggestions.js
this is needed for when suggestion popup is going outside of iframe
=> [mentions-plugin] add repositioning option

CHANGELOG.md, packages/editor/statics/locale/messages_en.json, packages/plugin-sound-cloud/package.json, packages/plugin-sound-cloud/src/toolbar/insert-buttons.jsx, packages/plugin-sound-cloud/src/toolbar/soundCloudURLInputModal.jsx
Fix soundcloud modal in mobile view
=> Fix soundcloud modal layout in mobile view

CHANGELOG.md, docs/plugin-development-guidelines/ModalDialogs.md, packages/common/src/Base/baseToolbarButton.jsx, packages/common/src/Base/createBaseInsertPluginButton.jsx, packages/common/src/Modals/RichContentModal.jsx, packages/common/src/consts.js, packages/common/src/index.js
=> Modal decoration API

CHANGELOG.md, packages/plugin-sound-cloud/src/toolbar/insert-buttons.jsx, packages/plugin-sound-cloud/statics/styles/default-sound-cloud-styles.scss
=> Sound cloud view mobile fixes

CHANGELOG.md, packages/editor/src/RichContentEditor/RichContentEditor.jsx, packages/editor/src/RichContentEditor/getBlockRenderMap.js, packages/viewer/src/Preview.jsx
=> SEO demand: render list item content wrapped in <p> tags

packages/plugin-giphy/statics/styles/giphy-modal-arrow.scss
=> (giphy-plugin-fix)Hide arrow on mobile view

CHANGELOG.md, packages/common/src/Utils/urlValidators.js, packages/plugin-sound-cloud/src/toolbar/soundCloudURLInputModal.jsx, packages/plugin-sound-cloud/statics/styles/sound-cloud-url-input-modal.scss
- Text input fixes
- Button font fixes
=> Soundcloud fix product review

CHANGELOG.md, packages/plugin-video/src/toolbar/videoSelectionInputModal.jsx, packages/plugin-video/statics/styles/video-selection-input-modal.scss
-Text input error icon padding fix
-Text input shadow fix on safari
=> VideoPlugin styles fix 

CHANGELOG.md, packages/plugin-giphy/package.json, packages/plugin-giphy/src/giphy-viewer.jsx
=> img tag used instead of gifplayer as it doesnt use self closing img tag

CHANGELOG.md, packages/plugin-giphy/src/classNameStrategies.js, packages/plugin-giphy/src/giphy-component.jsx, packages/plugin-giphy/src/giphy-viewer.jsx, packages/plugin-giphy/src/icons/InsertPluginIcon.jsx, packages/plugin-giphy/src/index.js, packages/plugin-giphy/src/typeMapper.js, packages/plugin-giphy/statics/styles/giphy-viewer.scss
- Remove container styles to keep width to hight ratio of each giphy
=> Giphy viewer fix

CHANGELOG.md, packages/plugin-video/src/toolbar/videoSelectionInputModal.jsx, packages/plugin-video/statics/styles/video-selection-input-modal.scss
- handle input selection focus on iphone
- setting border radius of input to 0 on iphone
=> Video plugin fix

CHANGELOG.md, packages/common/src/Utils/urlValidators.js, packages/common/src/index.js, packages/plugin-sound-cloud/src/soundCloud-viewer.jsx, packages/plugin-sound-cloud/src/toolbar/insert-buttons.jsx, packages/plugin-sound-cloud/src/toolbar/soundCloudURLInputModal.jsx
- handle input selection focus on iphones 
- mathcing soundcloud url to viewer & clip prefix url shared text
=> Fix sound cloud mobile issues

examples/viewer/src/App.jsx, examples/viewer/src/TestData/initial-state.js, packages/plugin-code-block/src/PrismDecorator.js, packages/plugin-code-block/src/viewer.js, packages/viewer/src/Preview.jsx, packages/viewer/src/RichContentViewer.jsx
=> Adds code block viewer support

examples/viewer/src/App.jsx, examples/viewer/src/TestData/initial-state.js, examples/viewer/src/theme/mentions.theme.scss, examples/viewer/src/theme/theme.js, packages/plugin-mentions/src/MentionComponent.jsx, packages/plugin-mentions/src/MentionViewer.jsx, packages/plugin-mentions/src/createMentionsPlugin.js, packages/plugin-mentions/src/defaultSettings.js, packages/plugin-mentions/src/typeMapper.js, packages/plugin-mentions/src/types.js, packages/plugin-mentions/src/viewer.js
=> Mentions viewer

CHANGELOG.md, examples/viewer/src/TestData/initial-state.js, packages/viewer/src/Preview.jsx, packages/viewer/src/RichContentViewer.jsx
=> fix soft new line at end of block

CHANGELOG.md, packages/viewer/statics/rich-content-viewer.scss
=> Fix viewer justified text

CHANGELOG.md, packages/common/src/Utils/draftUtils.js
Base on draft.js official [example](https://github.com/facebook/draft-js/blob/master/examples/draft-0-10-0/tex/js/modifiers/removeTeXBlock.js)
=> Fix removeBlock

packages/viewer/src/Preview.jsx
=> Prevent prop mutation in Preview.jsx

CHANGELOG.md, packages/plugin-video/src/toolbar/videoSelectionInputModal.jsx, packages/plugin-video/statics/styles/video-selection-input-modal.scss
- Remove font family scss property so theme could be applied to header text. 
- Fix text input alignment pixels
=> Video Style Fix

packages/plugin-button/src/components/custom-color-picker.jsx, packages/plugin-button/statics/styles/custom-color-picker.scss
=> Wix rich content plugin button issues

.eslintrc, .vscode/extensions.json, .vscode/settings.json, CHANGELOG.md, package-lock.json, package.json, prettier.config.js
=> [*] infra(prettier)

CHANGELOG.md, docs/PluginCustomization.md, packages/plugin-giphy/src/toolbar/insert-giphy-buttons.jsx
Will update changelog etc later, wanted to see what you thought about the change and more importantly the naming of the config keys.
=> [giphy] Add extra customization options to giphy plugin

CHANGELOG.md, packages/common/src/Base/createBaseComponent.jsx, packages/common/statics/styles/global.scss, packages/viewer/src/PluginsViewer.jsx
fixes https://jira.wixpress.com/browse/NWB-163
=> Atomic Links - wrap instead of positionining sibling

CHANGELOG.md, packages/plugin-html/src/HtmlComponent.jsx
=> HTML use 'auto' width on mobile

CHANGELOG.md, packages/plugin-image/src/classNameStrategies.js, packages/plugin-image/src/image-component.jsx, packages/viewer/statics/rich-content-viewer.scss
=> Image - fix original size support for mobile cuts off full size images

CHANGELOG.md, examples/editor/package.json, examples/editor/src/Plugins.jsx, examples/editor/src/PluginsConfig.js, examples/viewer/package.json, examples/viewer/src/App.jsx, package-lock.json, packages/plugin-headers-markdown/package.json, packages/plugin-headers-markdown/src/createHeadersMarkdownPlugin.js, packages/plugin-headers-markdown/src/decorator.jsx, packages/plugin-headers-markdown/src/index.js, packages/viewer/src/List.jsx, packages/viewer/src/Preview.jsx
=> Headers markdown

CHANGELOG.md, packages/plugin-image/src/get-wix-media-url.js, packages/plugin-image/src/image-viewer.jsx
=> image -reduce default preload size

CHANGELOG.md, packages/viewer/src/RichContentViewer.jsx, packages/viewer/src/index.js, packages/viewer/src/utils/convertToHTML.jsx, packages/viewer/statics/rich-content-viewer.scss
=> [viewer] convertToHTML

CHANGELOG.md, packages/viewer/src/Preview.jsx, packages/viewer/src/RichContentViewer.jsx, packages/viewer/src/index.js, packages/viewer/statics/rich-content-viewer.scss
Reverts wix-incubator/rich-content#254
=> Revert "[viewer] convertToHTML"

CHANGELOG.md, packages/common/package.json, packages/editor/package.json, packages/plugin-code-block/package.json, packages/plugin-divider/package.json, packages/plugin-emoji/package.json, packages/plugin-giphy/package.json, packages/plugin-hashtag/package.json, packages/plugin-html/package.json, packages/plugin-html/statics/html-plugin-embed.html, packages/plugin-image/package.json, packages/plugin-link/package.json, packages/plugin-mentions/package.json, packages/plugin-sound-cloud/package.json, packages/plugin-video/package.json, packages/viewer/package.json
=> fix instagram cut off in html-plugin

.travis.yml, CHANGELOG.md, package.json, scripts/deployExamples.js, scripts/publishPackages.js
=> CI deploy examples

CHANGELOG.md, examples/editor/src/theme/plugin-link.theme.scss, examples/editor/src/theme/theme.js, examples/main/src/theme/plugin-link.theme.scss, examples/main/src/theme/theme.js, examples/main/src/viewer/Viewer.jsx, examples/viewer/src/theme/plugin-link.theme.scss, examples/viewer/src/theme/theme.js, packages/common/statics/styles/global.scss, packages/viewer/src/PluginsViewer.jsx
=> fix plugin link height issues

CHANGELOG.md, packages/common/src/Utils/Context.js, packages/editor/src/RichContentEditor/RichContentEditor.jsx, packages/viewer/src/RichContentViewer.jsx
=> fix context rerender

CHANGELOG.md, packages/plugin-video/src/video-component.jsx, packages/plugin-video/src/video-viewer.jsx, packages/plugin-video/statics/styles/video-viewer.scss
=> fix video ratio

CHANGELOG.md, packages/common/src/Base/createBaseInsertPluginButton.jsx, packages/common/src/Base/createBaseToolbar.jsx, packages/editor/src/RichContentEditor/Toolbars/InlineToolbar/InlineToolbar.jsx, packages/editor/src/RichContentEditor/Toolbars/SideToolbar/SideToolbar.jsx, packages/editor/src/RichContentEditor/Toolbars/StaticToolbar/StaticToolbar.jsx
There was a lot of unnecessary work (rerendering toolbars) on every keystroke.
=> Improve performance

CHANGELOG.md, packages/plugin-image/src/image-viewer.jsx
Fixes regression introduced in: https://github.com/wix-incubator/rich-content/commit/42e7f4289fc3e4236dc9d36bdc631b012beb6b60#diff-de64141af8efc178103202455367fe21L42
=> [image] fix regression

CHANGELOG.md, babel.config.js, examples/main/.babelrc, examples/main/package.json, examples/main/src/App.jsx, examples/main/src/Components/SectionHeader.jsx, examples/main/src/editor/Editor.jsx, examples/main/src/getAllLocales.js, examples/main/src/index.js, examples/main/src/styles.global.scss, examples/main/src/utils.js
=> change locales in the example

CHANGELOG.md, packages/editor/src/RichContentEditor/getBlockRenderMap.js
=> Fix spacing in numbered list

CHANGELOG.md, packages/viewer/web/src/utils/convertContentState.jsx
=> fix justified text empty new lines disappear

CHANGELOG.md, packages/plugin-gallery/web/package.json, packages/plugin-gallery/web/src/helpers/resize-media-url.js
=> gallery resize media url absolute url

CHANGELOG.md, packages/plugin-gallery/web/src/gallery-viewer.jsx
=> Fix/gallery re-render gallery on componentData change only

CHANGELOG.md, packages/plugin-gallery/web/src/components/gallery-controls/gallery-items-sortable.js
…mage-settings returns to gallery settings
=> gallery/bug fix: delete last remaining image returns to gallery-settings

CHANGELOG.md, packages/plugin-gallery/web/src/constants.js, packages/plugin-gallery/web/src/gallery-viewer.jsx, packages/plugin-gallery/web/src/helpers/layout-data-provider.js
=> [gallery] fix(gallery-viewer): height issues

CHANGELOG.md, packages/plugin-gallery/web/src/gallery-viewer.jsx
=> fix gallery height issues

CHANGELOG.md, examples/main/shared/editor/Editor.jsx, packages/editor/web/src/RichContentEditor/Toolbars/StaticToolbar/createMobileToolbar.jsx, packages/editor/web/src/RichContentEditor/Toolbars/StaticToolbar/createStaticToolbar.jsx, packages/editor/web/src/RichContentEditor/Toolbars/default-toolbar-settings.js, packages/editor/web/statics/styles/mobile-toolbar.scss, packages/editor/web/statics/styles/static-toolbar.scss
=> sticky mobileToolbar and marking text doesn't show another inlineToolbar

CHANGELOG.md, packages/editor/web/src/RichContentEditor/Toolbars/InlineToolbar/InlineToolbar.jsx, packages/editor/web/src/RichContentEditor/Toolbars/InlineToolbar/createInlineTextToolbar.jsx, packages/editor/web/src/RichContentEditor/Toolbars/InlineToolbar/createInlineToolbar.jsx, packages/editor/web/src/RichContentEditor/Toolbars/StaticToolbar/createMobileToolbar.jsx
=> fix the inline and mobile toolbars buttons directions on RTL display

CHANGELOG.md, package-lock.json, packages/editor/web/statics/styles/draft.rtlignore.scss
=> the indentation in editor works

CHANGELOG.md, examples/main/shared/editor/EditorPlugins.jsx, examples/main/shared/viewer/ViewerPlugins.jsx, examples/main/src/ExampleApp.jsx, packages/plugin-gallery/web/src/gallery-viewer.jsx
The scrollingElement prop can be optionally passed by users to the gallery plugin.
default value = window, can override with a dom element reference.
=> gallery fix: panorama layout displays all items

CHANGELOG.md, packages/plugin-gallery/web/src/constants.js, packages/plugin-gallery/web/src/gallery-viewer.jsx
=> fix gallery alignment

lerna.json, scripts/deployExamples.js, scripts/publishPackages.js
=> version, publish, deploy only on release branch

CHANGELOG.md, packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
=> fix focus in editor

CHANGELOG.md, packages/editor/web/src/RichContentEditor/Decorators/Resize/createDecorator.js
- `editor`
- resize-decorator is not activated on mobile
=> Resize decorator is not activated on mobile

packages/plugin-html/web/src/HtmlComponent.jsx
=> [html] fix(HtmlComponent) calculated height applied on ViewportRenderer

CHANGELOG.md, packages/plugin-gallery/web/package.json
=> update pro-gallery 1.5.25

CHANGELOG.md, packages/plugin-video/web/src/toolbar/inline-video-buttons.jsx, packages/plugin-video/web/src/toolbar/insert-video-buttons.jsx, packages/plugin-video/web/src/toolbar/videoSelectionInputModal.jsx, packages/plugin-video/web/statics/styles/video-selection-input-modal.scss
=> Adds file upload support

CHANGELOG.md, examples/main/shared/editor/EditorPlugins.jsx, packages/plugin-mentions/web/src/MentionSuggestionsWrapper.jsx
=> mentions external dropdown control

CHANGELOG.md, packages/plugin-gallery/web/package.json
=> pro-gallery updated to 1.5.33

e2e/cypress/support/commands.js, e2e/tests/plugins.e2e.js
=> fix unstable tooltips

CHANGELOG.md, examples/main/shared/editor/EditorPlugins.jsx, packages/plugin-image/web/src/imageStudio/image-editor.jsx, packages/plugin-image/web/src/toolbar/createToolbar.js, packages/plugin-image/web/src/toolbar/inline-buttons.jsx
=> image editor launched callback

CHANGELOG.md, packages/plugin-video/web/src/toolbar/videoSelectionInputModal.jsx
=> Fixes video file selection

packages/plugin-giphy/web/src/giphy-viewer.jsx
=> Hotfix for giphy plugin

examples/main/shared/editor/EditorPlugins.jsx
=> example: emoji styles imported

CHANGELOG.md, packages/fullScreen/web/src/lib/getImagesData.js
=> Hotfix for fullscreen

CHANGELOG.md, package-lock.json, package.json, packages/editor-common/web/src/Utils/draftUtils.js, packages/editor-common/web/src/index.js, packages/plugin-emoji/web/src/modifiers/addEmoji.js
=> emoji delete bug fix

CHANGELOG.md, packages/editor/web/src/RichContentEditor/RichContentEditor.jsx, packages/editor/web/src/RichContentEditor/keyBindings.js, packages/plugin-code-block/web/src/createCodeBlockPlugin.js
=> fix [onTab warning]: createCodeBlockPlugin

README.md
=> docs(README): First time flow

CHANGELOG.md, docs/UiSettings.md, examples/main/shared/editor/EditorPlugins.jsx, packages/editor-common/web/src/Components/LinkPanel.jsx, packages/plugin-gallery/web/src/components/gallery-controls/gallery-image-settings.js, packages/plugin-image/web/src/toolbar/image-settings.js
=> Link custom place holder

examples/main/shared/theme/toolbars/inline-toolbar.theme.scss, packages/editor/web/src/RichContentEditor/Toolbars/buttons/utils/createTextDropdownButton.jsx
=> bug:[hoverAligmentIconColor] createTextDropdownButton

e2e/cypress/support/index.js, e2e/tests/__snapshots__/plugins.e2e.js.snap, e2e/tests/plugins.e2e.js
=> Dec9 full screen tests

CHANGELOG.md, packages/editor-common/web/statics/styles/color-picker.scss, packages/plugin-text-color/web/src/toolbar/TextColorPanel.jsx
=> [Color picker] fix/ResetToDefault button sticky to bottom

scripts/deployExamples.js
=> fix(deployExamples): prevent illegal surge names

CHANGELOG.md, packages/editor-common/web/src/Utils/draftUtils.js
=> fix(draftUtils): editing link settings

CHANGELOG.md, packages/editor-common/web/statics/styles/dropdown.scss
=> [editor-common] fix gallery dropdown css

CHANGELOG.md, examples/main/shared/editor/EditorPlugins.jsx, packages/editor-common/web/src/Components/ColorPicker/ColorPicker.jsx, packages/editor-common/web/statics/styles/color-picker.scss, packages/plugin-text-color/web/src/toolbar/TextColorPanel.jsx
=> [colorPicker] new colors are added to the end of the list + 'reset to default' removes from the 'inlineStyleRanges' in the content state

.github/workflows/actions.yml
=> example feat: example

CHANGELOG.md, packages/plugin-giphy/web/src/giphy-viewer.jsx, packages/plugin-html/web/src/HtmlComponent.jsx, packages/plugin-map/web/src/MapViewer.jsx, packages/plugin-sound-cloud/web/src/soundCloud-viewer.jsx, packages/plugin-video/web/src/video-viewer.jsx
- `general`
- `ViewportRenderer` disabled for all the plugins
=> ViewportRenderer disabled for all the plugins

CHANGELOG.md, packages/plugin-gallery/web/src/gallery-component.jsx, packages/plugin-gallery/web/src/gallery-viewer.jsx, packages/plugin-html/web/src/HtmlComponent.jsx, packages/plugin-image/web/src/InPluginInput.jsx, packages/plugin-image/web/src/image-component.jsx, packages/plugin-image/web/src/image-viewer.jsx, packages/plugin-image/web/statics/styles/image-viewer.scss, packages/plugin-sound-cloud/web/src/soundCloud-viewer.jsx, packages/plugin-sound-cloud/web/src/soundCloud.jsx, packages/plugin-video/web/src/video-component.jsx, packages/plugin-video/web/src/video-viewer.jsx
- `image`
- defaults for editor-only props in image-viewer
=> image: in-plugin editing default props

examples/main/package.json, examples/storybook/package.json, examples/viewer-ssr/package.json, packages/common/web/package.json, packages/editor-common/web/package.json, packages/editor/web/package.json, packages/fullScreen/web/package.json, packages/plugin-button/web/package.json, packages/plugin-code-block/web/package.json, packages/plugin-divider/web/package.json, packages/plugin-emoji/web/package.json, packages/plugin-file-upload/web/package.json, packages/plugin-gallery/web/package.json, packages/plugin-giphy/web/package.json, packages/plugin-hashtag/web/package.json, packages/plugin-headers-markdown/web/package.json, packages/plugin-html/web/package.json, packages/plugin-image/web/package.json, packages/plugin-line-spacing/web/package.json, packages/plugin-link/web/package.json, packages/plugin-map/web/package.json, packages/plugin-mentions/web/package.json, packages/plugin-sound-cloud/web/package.json, packages/plugin-text-color/web/package.json, packages/plugin-undo-redo/web/package.json, packages/plugin-video/web/package.json, packages/preview/web/package.json, packages/viewer/web/package.json, packages/wrapper/web/package.json, plugins-bundle-analyzer/package.json
=> [all] refactor(package.json): match dependencies versions to root package.json

CHANGELOG.md, e2e/tests/fixtures/old-image-format.json, packages/common/web/src/Utils/normalization/dataNormalizers/imageDataNormalizer.js
=> [image]fix(normalizer): old data support

CHANGELOG.md, packages/plugin-gallery/web/package.json
=> [pro-gallery] bump version (1.7.25)

CHANGELOG.md, packages/editor-common/web/src/Utils/draftUtils.js
=> [editor] fix: prevent underline link inline style to affects new line

CHANGELOG.md, packages/editor-common/web/src/Components/LinkPanelContainer.jsx, packages/plugin-link/web/src/toolbar/TextLinkPanel.jsx
=> fix: when canceling link panel the selection jump

packages/fullScreen/web/package.json, rollup.config.common.js
=> fix(storybook + wrapper): cjs files & npm run watch

.github/labeler.yml, .github/workflows/label.yml, examples/main/shared/viewer/Viewer.jsx
=> Add Labeler action for breaking change detection

package-lock.json, package.json
=> [dependencies] fix(cypress): v.4.2.0 bug - fixed to v.4.1.0

CHANGELOG.md, packages/editor/web/src/lib/editorStateConversion.js, plugins-bundle-analyzer/analyzeBundles.js, plugins-bundle-analyzer/src/editorStateConversion.js
=> ready for merge

examples/main/shared/theme/text-link.theme.scss, package-lock.json, packages/plugin-link/web/src/createLinkPlugin.js, packages/wrapper/web/src/themeStrategy/ThemeGenerator.js
=> [wrapper] improve(theming): footer & link fix

CHANGELOG.md, packages/wrapper/web/src/localeStrategy/localeStrategyProvider.js
=> [wrapper] fix(localeStrategy): removed override of props

CHANGELOG.md, e2e/tests/fixtures/intro.json, packages/plugin-text-color/web/src/viewer.js
=> [wrapper + storybook] fix(plugins): removed empty typeMappers & updated storybook example

CHANGELOG.md, package-lock.json, packages/wrapper/web/src/FullscreenRenderer.js, packages/wrapper/web/src/ModalRenderer.js
=> [wrapper] fix(ssr): suspense render issue

CHANGELOG.md, packages/editor-common/web/src/Utils/draftUtils.js, packages/editor-common/web/src/index.js, packages/plugin-code-block/web/src/toolbar/blockTypeModifiers.js
=> code block initial state

e2e/tests/__snapshots__/plugins.e2e.js.snap, e2e/tests/plugins.e2e.js, packages/plugin-link-preview/web/src/lib/utils.js
=> [link-preview] fix: fix convert to link

packages/wrapper/web/src/EngineWrapper.js, packages/wrapper/web/src/FullscreenRenderer.js, packages/wrapper/web/src/ModalRenderer.js, packages/wrapper/web/src/RichContentWrapper.js
=> engine-wrapper code clean up

plugins-bundle-analyzer/src/wix-rich-content-plugin-link-preview.js
=> [bundle-analyzer]: fix link preview boundle analyze

CHANGELOG.md, packages/plugin-gallery/web/src/gallery-viewer.jsx
=> [plugin-gallery] fix:gallery plugin blurry pictures

e2e/test-env/src/client/app.css
rich-content: https://rich-content-fixTestsViewerSize.surge.sh/
rich-content-storybook: https://rich-content-storybook-fixTestsViewerSize.surge.sh/
=> [e2e] test-env viewer width

e2e/tests/fixtures/linkPreview.json, packages/plugin-link-preview/web/src/defaults.js
rich-content: https://rich-content-updateLinkPreviewDocumantation.surge.sh/
rich-content-storybook: https://rich-content-storybook-updateLinkPreviewDocumantation.surge.sh/
=> [link-preview]: update link preview storybook

CHANGELOG.md, e2e/tests/fixtures/intro.json
rich-content: https://rich-content-textHighlight-wrapper.surge.sh/
rich-content-storybook: https://rich-content-storybook-textHighlight-wrapper.surge.sh/
=> [storybook] fixed textHighlightPlugin color

CHANGELOG.md, e2e/cypress/support/commands.js, e2e/tests/plugins.e2e.js, e2e/tests/rendering.e2e.js, packages/plugin-gallery/web/src/gallery-viewer.jsx
rich-content: https://rich-content-fixGallery.surge.sh/
rich-content-storybook: https://rich-content-storybook-fixGallery.surge.sh/
=> [gallery] fix gallery

e2e/tests/fixtures/themeing-info.json
=> [storybook]: fix link preview display

CHANGELOG.md, packages/editor-common/web/src/Utils/draftUtils.js, packages/plugin-link/web/src/createLinkPlugin.js
rich-content: https://rich-content-fixLinkCheckboxes.surge.sh/
rich-content-storybook: https://rich-content-storybook-fixLinkCheckboxes.surge.sh/
=> [plugin-link] fix:save data of "target" and "rel" link(the checkboxes in Link Panel)

e2e/tests/__snapshots__/plugins.e2e.js.snap, e2e/tests/plugins.e2e.js, packages/plugin-link-preview/web/src/consts.js, packages/plugin-link-preview/web/src/lib/utils.js, packages/plugin-link/web/src/createLinkPlugin.js
rich-content: https://rich-content-linkPreviewFixes.surge.sh/
rich-content-storybook: https://rich-content-storybook-linkPreviewFixes.surge.sh/
=> Link preview fixes

CHANGELOG.md, packages/editor-common/web/src/Base/toolbars/toolbarUtils.js, packages/editor-common/web/src/Utils/getConfigByFormFactor.js, packages/editor-common/web/src/index.js, packages/editor/web/src/RichContentEditor/Toolbars/createEditorToolbars.js
rich-content: https://rich-content-Apr7-refactor-getConfigByFormFactor.surge.sh/
rich-content-storybook: https://rich-content-storybook-Apr7-refactor-getConfigByFormFactor.surge.sh/
=> refactor - remove getConfigByFormFactor.js

e2e/tests/plugins.e2e.js, packages/plugin-gallery/web/src/gallery-viewer.jsx
rich-content: https://rich-content-galleryFix.surge.sh/
rich-content-storybook: https://rich-content-storybook-galleryFix.surge.sh/
=> galleryImprove

CHANGELOG.md, packages/plugin-gallery/web/src/gallery-viewer.jsx
rich-content: https://rich-content-galleryFix.surge.sh/
rich-content-storybook: https://rich-content-storybook-galleryFix.surge.sh/
=> [gallery] scrollingElement fallback to window

packages/common/web/src/index.js, packages/common/web/src/lib/contentStateServices.js, packages/common/web/src/test/contentStateServices.spec.js
rich-content: https://rich-content-Apr12-truncateContentStateFunction.surge.sh/
rich-content-storybook: https://rich-content-storybook-Apr12-truncateContentStateFunction.surge.sh/
=> [common] add truncate content state function

CHANGELOG.md, e2e/tests/__snapshots__/text.e2e.js.snap, e2e/tests/text.e2e.js, packages/editor-common/web/src/Utils/draftUtils.js, packages/editor-common/web/src/consts.js, packages/editor-common/web/src/index.js, packages/editor/web/src/RichContentEditor/handleKeyCommand.js, packages/plugin-gallery/web/src/gallery-viewer.jsx
rich-content: https://rich-content-insertTabChar.surge.sh/
rich-content-storybook: https://rich-content-storybook-insertTabChar.surge.sh/
=> [editor-common] feat: insert tab character

e2e/tests/__snapshots__/plugins.e2e.js.snap, e2e/tests/fixtures/link-preview.json, e2e/tests/fixtures/linkPreview.json, examples/main/shared/theme/link-preview.theme.scss, examples/main/shared/utils/linkPreviewUtil.js, examples/storybook/src/RceTheme.js, packages/editor-common/web/src/Utils/draftUtils.js, packages/editor-common/web/src/index.js, packages/plugin-link-preview/web/src/LinkPreviewViewer.jsx, packages/plugin-link-preview/web/src/defaults.js, packages/plugin-link-preview/web/src/lib/utils.js, packages/plugin-link-preview/web/statics/styles/link-preview.scss
rich-content: https://rich-content-fixSnapshots.surge.sh/
rich-content-storybook: https://rich-content-storybook-fixSnapshots.surge.sh/
=> [test] internal:fix link preview snapshots

CHANGELOG.md, packages/wrapper/web/src/FullscreenRenderer.tsx, packages/wrapper/web/src/ModalRenderer.tsx
rich-content: https://rich-content-wrapper-refactor.surge.sh/
rich-content-storybook: https://rich-content-storybook-wrapper-refactor.surge.sh/
=> [wrapper] refactor (FullscreenRenderer.tsx, ModalRenderer.tsx)

.github/workflows/tests.yml, package-lock.json, package.json
rich-content: https://rich-content-e2e.surge.sh/
rich-content-storybook: https://rich-content-storybook-e2e.surge.sh/
=> fix github actions

CHANGELOG.md, e2e/tests/fixtures/nested-lists.json, packages/viewer/web/src/List.jsx
rich-content: https://rich-content-inlineStylesLists.surge.sh/
rich-content-storybook: https://rich-content-storybook-inlineStylesLists.surge.sh/
=> [viewer] fix: inline styles in lists  breaking viewer

.github/workflows/tests.yml
rich-content: https://rich-content-notify-recovery-on-slack.surge.sh/
rich-content-storybook: https://rich-content-storybook-notify-recovery-on-slack.surge.sh/
=> Notify build recovered

babel.config.js, package.json
rich-content: https://rich-content-addNullishCoalescing.surge.sh/
rich-content-storybook: https://rich-content-storybook-addNullishCoalescing.surge.sh/
=> add nullish-coalescing

CHANGELOG.md, packages/plugin-code-block/web/src/toolbar/blockTypeModifiers.js
rich-content: https://rich-content-code-block-select-back.surge.sh/
rich-content-storybook: https://rich-content-storybook-code-block-select-back.surge.sh/
=> fix backward code block

CHANGELOG.md, scripts/publishPackages.js
=> [*] feat(publishPackages): custom npm tag

.github/workflows/commitAfterMerge.yml
=> trigger actions- Only for testing

.github/workflows/commitAfterMerge.yml
=> trigger actions

.github/workflows/commitAfterMerge.yml
=> GitHub action on merge pr new

.github/workflows/commitAfterMerge.yml
=> GitHub action on merge pr

e2e/tests/text.e2e.js
rich-content: https://rich-content-Apr6-addTestsToLinkToolbar.surge.sh/
rich-content-storybook: https://rich-content-storybook-Apr6-addTestsToLinkToolbar.surge.sh/
=> [e2e] add more tests to link toolbar

.github/workflows/commitAfterMerge.yml, plugins-bundle-analyzer/package.json
=> Tmp branch

.github/workflows/commitAfterMerge.yml, plugins-bundle-analyzer/package.json
=> Tmp pull request

packages/editor/web/src/RichContentEditor/Toolbars/SideToolbar/AddPluginFloatingToolbar.jsx, packages/editor/web/src/RichContentEditor/Toolbars/SideToolbar/AddPluginMenu.js, packages/editor/web/src/RichContentEditor/Toolbars/SideToolbar/SideToolbarPluginsSection.js
=> [merge styles] internal: fix theme warning

e2e/tests/rtl.e2e.js, e2e/tests/settings.js, e2e/tests/testFixtures.js
=> [test-env]: fix link preview rendering test

CHANGELOG.md, examples/main/shared/editor/Editor.jsx, examples/main/shared/editor/EditorPlugins.jsx, examples/storybook/stories/Toolbars/PluginMenuStory.js, packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
=> hotfix: getToolbarSettings Api fix

packages/editor/web/statics/styles/side-toolbar-panel.scss
=> [plugin-menu] fix: ui fixes

examples/storybook/stories/Plugins/VerticalEmbed/VerticalEmbedEditor.js, examples/storybook/stories/Plugins/VerticalEmbed/VerticalEmbedStory.js, examples/storybook/stories/Plugins/VerticalEmbed/index.js, examples/storybook/stories/Plugins/apiData.js, examples/storybook/stories/Plugins/index.js
=> [vertical-embed]: add vertical embed plugin to storybook

packages/plugin-sound-cloud/web/src/toolbar/insert-buttons.jsx
=> [plugin-menu]: move soundCloud plugin to social embed section

packages/plugin-link-preview/web/src/LinkPreviewViewer.jsx
=> [link-preview] fix: mobile ui fix

examples/storybook/stories/Components/EditorWrapper.js, examples/storybook/stories/TestCase/GroupsStory.js, examples/storybook/stories/TestCase/GroupsStory.scss, examples/storybook/stories/TestCase/index.js, examples/storybook/stories/Toolbars/PluginMenuStory.js, examples/storybook/stories/index.js
A way to simulate groups behavior in storybook, according to UX request
=> [Storybook] Groups example

e2e/test-env/src/server/renderer.jsx
=> [test-env] fix: fix test env to work without testAppConfig query param

packages/editor-common/web/src/Utils/getModalStyles.js, packages/editor-common/web/statics/styles/url-input-modal.scss
=> [social-modals] fix: X button position in mobile

examples/main/shared/theme/plugin-link.theme.scss
=> [exampleApp-viewer] fix: remove dashed border from linkable items

examples/storybook/stories/Toolbars/PluginMenuStory.js
=> [plugin-menu] fix: fix broken storybook

CHANGELOG.md, examples/main/shared/preview/Preview.jsx, examples/main/shared/viewer/Viewer.jsx, package-lock.json, packages/plugin-gallery/web/src/gallery-viewer.jsx, packages/plugin-image/web/src/image-viewer.jsx, packages/wrapper/web/tsconfig.json
Squashed from #1088 to solve test issues
=> [viewer] bi(callbacks): onExpand image & gallery

plugins-bundle-analyzer/bundlesSizesBaseline.json
=> Commit after merge -testing

.github/workflows/commitAfterMerge.yml, plugins-bundle-analyzer/bundlesSizesBaseline.json
=> Commit after merge - testing

CHANGELOG.md, packages/editor/web/src/RichContentEditor/createPlugins.jsx, packages/editor/web/statics/styles/resizeable.rtlignore.scss
=> [image] resize Image: change the manual minimum size of an image to 20px

CHANGELOG.md, package-lock.json, packages/editor-common/web/package.json, packages/editor-common/web/src/Components/LinkPanelDropdown.jsx, plugins-bundle-analyzer/bundlesSizesBaseline.json
=> Dynamic import to react-window and Downshift

CHANGELOG.md, packages/editor-common/web/src/Components/TextInput.jsx, packages/plugin-html/web/src/toolbar/HtmlEditPanel.jsx
=> [html-plugin]fix: embed website url bug fix

examples/main/shared/editor/EditorPlugins.jsx, examples/storybook/stories/Plugins/VerticalEmbed/VerticalEmbedEditor.js, examples/storybook/stories/Plugins/apiData.js, packages/plugin-vertical-embed/web/src/toolbar/postSelectionInputModal.jsx
=> Fetch verticals on mount

examples/storybook/stories/Components/StoryParts.js
=> [storybook] fix story title undefined

e2e/cypress/support/commands.js, e2e/tests/__snapshots__/text.e2e.js.snap, e2e/tests/text.e2e.js, packages/editor-common/web/src/Components/LinkPanel.jsx, packages/editor-common/web/src/Components/LinkPanelDropdown.jsx
=> [plugin-link] fix: input auto focus

CHANGELOG.md, packages/plugin-gallery/web/package.json
request in https://app.asana.com/0/1160368252184537/1178817531833089
=> bump plugin-gallery to 1.10.19

examples/storybook/stories/Components/EditorWrapper.js
=> [storybook] fix: vertical embed bug

CHANGELOG.md, packages/editor-common/web/src/Base/buttons/BlockLinkButton.jsx
=> [plugin-image] fix: insert link to image close toolbar

e2e/tests/plugins.e2e.js, examples/main/shared/editor/EditorPlugins.jsx
=> [test] fix: fix adsense test fail

examples/storybook/stories/Plugins/HtmlPlugin/HtmlWithDomainStory.js
=> [storybook]: add adsense plugin to html story

CHANGELOG.md, e2e/tests/__snapshots__/media.e2e.js.snap, e2e/tests/fixtures/image-with-loader-percent.json, e2e/tests/media.e2e.js, packages/plugin-image/web/src/image-component.jsx
=> [plugin-image] add fake loader to image (oneApp)

CHANGELOG.md, packages/common/web/src/Utils/textDirection.js
=> getDirectionFromAlignmentAndTextDirection fixed

CHANGELOG.md, packages/editor-common/web/package.json, packages/editor-common/web/src/Base/createBasePlugin.jsx, packages/editor/web/package.json, packages/plugin-hashtag/web/src/createHashtagPlugin.js, packages/plugin-mentions/web/src/createMentionsPlugin.js
PR by @bchmn to support mobile composition mode using decorators (@ in mentionns or # in hashtags)
=> [editor] feat(createBasePlugin): support decorator feature

package-lock.json, packages/common/web/tsconfig.json, packages/ricos-common/web/src/index.ts, plugins-bundle-analyzer/bundlesSizesBaseline.json, tsconfig.json
=> [ricos-common] fix(index): import types from common package

CHANGELOG.md, e2e/cypress/support/commands.js, e2e/tests/__snapshots__/media.e2e.js.snap, e2e/tests/media.e2e.js, e2e/tests/rtl.e2e.js, e2e/tests/text.e2e.js
=> update setSelection for editor and viewer

e2e/tests/fixtures/link-preview-render.json, e2e/tests/fixtures/link-preview.json, e2e/tests/settings.js, packages/editor/web/src/RichContentEditor/Toolbars/SideToolbar/AddPluginFloatingToolbar.jsx
=> [link-preview-test] fix: fix test failure

packages/common/web/statics/locale/messages_en.json
=> There's a new key for Code Block, there's already a key for it.

packages/editor-common/web/src/Base/baseToolbarButton.jsx, packages/editor-common/web/src/Base/buttons/createBlockAlignmentAndSizeButton.jsx, packages/editor-common/web/src/Base/buttons/createBlockAlignmentButton.jsx, packages/editor-common/web/src/Base/buttons/createBlockButton.jsx, packages/editor-common/web/src/Base/buttons/createBlockSizeButton.jsx, packages/editor-common/web/src/Base/createBaseInsertPluginButton.jsx, packages/editor-common/web/src/Components/InlineToolbarButton.jsx, packages/editor-common/web/src/Components/ToolbarButton.jsx, packages/editor-common/web/src/Utils/generateInsertPluginButtonProps.js, packages/editor/web/src/RichContentEditor/Toolbars/buttons/TextButton.jsx, packages/editor/web/src/RichContentEditor/Toolbars/buttons/TextLabelButton.jsx
=> [editor] fix(insert-button-props) plugin menu ref, tooltips

packages/editor-common/web/src/Utils/getModalStyles.js, packages/editor/web/src/RichContentEditor/Toolbars/StaticToolbar/StaticToolbar.jsx, packages/plugin-html/web/src/toolbar/insert-buttons.ts
=> [adsense-plugin]fix: adsense plugin insert button tooltip

packages/editor/web/src/RichContentEditor/Toolbars/StaticToolbar/MoreButton.js, packages/editor/web/statics/styles/static-toolbar-more-button.scss
=> [more plugin menu]fix: fix plugin menu positions

bundle-analyzer/bundlesSizesBaseline.json, packages/plugin-giphy/web/statics/styles/giphy-selecter.scss
=> [giphy-plugin] fix: fix gif height

CHANGELOG.md, packages/editor-common/web/statics/styles/anchor-panel.scss
=> [plugin-link] fix: position of anchor dropdown filter

CHANGELOG.md, packages/plugin-image/web/src/image-viewer.jsx
=> [plugin-image] fix: link in image viewer

CHANGELOG.md, packages/plugin-link/web/src/LinkViewer.jsx
=> [plugin-link] fix: link viewer onClick function (from settings)

e2e/tests/fixtures/anchorable-plugins.json
=> [storybook] add example to anchor story

packages/editor/web/src/RichContentEditor/Toolbars/StaticToolbar/MoreButton.js, packages/editor/web/src/RichContentEditor/Toolbars/StaticToolbar/StaticToolbar.jsx
=> [shortcut-menu]fix: fix icon color on dark mode

packages/common/web/lib/debugging-info.js
=> [common] fix(debugging-info) protect window access

CHANGELOG.md, packages/editor-common/web/src/Components/InputWithLabel.jsx, packages/plugin-image/web/src/image-viewer.jsx
=> [image] fix(image-viewer): caption in rtl

CHANGELOG.md, packages/editor-common/web/src/Components/RadioGroup.jsx
=> fix RadioGroup button

packages/editor/web/src/RichContentEditor/InnerRCE.jsx, packages/editor/web/src/RichContentEditor/RichContentEditor.jsx, packages/editor/web/src/RichContentEditor/externalToolbarPlugin.js
=> [inner-rce] set editing mode from outer rce onBlur

packages/editor/web/src/RichContentEditor/InnerRCE.jsx, packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
=> [inner-rce] fix rce onFocus + onBlur

CHANGELOG.md, packages/preview/web/src/Components/ReadMore.jsx
=> ReadMore click expands the full content

packages/editor/web/src/RichContentEditor/InnerRCE.jsx
=> [inner-rce] remove static & mobile toolbars

CHANGELOG.md, packages/preview/web/src/Components/default-transformation.js
=> [preview] fix(readMore): visibility issue

packages/editor/web/src/RichContentEditor/InnerRCE.jsx
=> [inner-rce] receive new editorState from plugin

CHANGELOG.md, packages/editor/web/statics/styles/side-toolbar-panel.scss, packages/plugin-giphy/web/src/toolbar/giphyEmptyState.js, packages/plugin-giphy/web/statics/styles/giphy-selecter.scss
=> [modals empty-state]fix: side menu and gif empty state ui fux

packages/editor/web/src/RichContentEditor/InnerRCE.jsx
=> [inner-rce] remove anchor from inner rce links

bundle-analyzer/bundlesSizesBaseline.json, packages/editor/web/src/RichContentEditor/InnerRCE.jsx, packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
=> [inner-rce] add readOnly prop + fix text color

package-lock.json, packages/editor-common/web/package.json
=> [editor-common] infra(package) draft@0.0.10

examples/main/shared/editor/Editor.jsx, packages/editor/web/src/RichContentEditor/InnerRCE.jsx, packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
=> [inner-rce] fix mobile & static toolbars

CHANGELOG.md, packages/editor/web/src/RichContentEditor/Toolbars/buttons/utils/generateTextToolbarButtonProps.js, packages/plugin-headings/web/src/toolbar/createToolbar.tsx
- `editor`
- external toolbars: inline style toggling fixed
=> [editor] fix inline style toggling

CHANGELOG.md, packages/editor-common/web/statics/styles/link-panel.scss
=> [link] fix: basic link panel wiring

packages/plugin-commons/web/statics/styles/url-input-modal.scss
=> [plugin-commons] fix styles

packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
=> [inner-rce] fix static toolbars

packages/editor/web/src/RichContentEditor/RichContentEditor.jsx, packages/editor/web/src/RichContentEditor/handlePastedText.js
=> [inner-rce] remove plugins on paste

CHANGELOG.md, e2e/tests/fixtures/storybook-example-app.json, examples/storybook/stories/palettesExample.js, packages/common/web/src/types/themeTypes.ts, packages/editor/web/src/RichContentEditor/Toolbars/SideToolbar/AddPluginMenu.js, packages/plugin-button/web/src/defaults.ts, packages/plugin-link-preview/web/src/defaults.ts, packages/ricos-theme/web/src/ThemeGenerator.ts, packages/ricos-theme/web/src/palettes/utils.ts, packages/ricos-theme/web/src/themes/editor-common.ts, packages/ricos-theme/web/src/themes/editor.ts, packages/ricos-theme/web/src/themes/utils.ts
- plugin menu color fix
- resize handles color fix
- brightness threshold to activate fallback color - raised
- removed unused-by-design colors from palette (secondary, color4, color7)
=> [ricos-theme] fixes & updates

e2e/cypress/support/commands.js
=> e2e: remove user agent

examples/storybook/package.json, yarn.lock
=> [storybook] update WSR version

CHANGELOG.md, packages/plugin-gallery/web/package.json
=> [gallery] bump version to 2.144

package.json, yarn.lock
Reverts wix-incubator/rich-content#1636
=> Revert "build(deps-dev): bump html-webpack-plugin from 3.2.0 to 4.5.0"

CHANGELOG.md, docs/docs/plugins_api/MapPlugin.mdx
https://jira.wixpress.com/browse/ASST-3204 Fix this security issue with google api key.
=> [docs] fix google api key security issue

package.json, yarn.lock
Reverts wix-incubator/rich-content#1620
=> Revert "build(deps-dev): bump husky from 4.2.4 to 4.3.0"

CHANGELOG.md, packages/plugin-gallery/web/package.json
improved version of the LayoutFixer for the blog
=> [gallery] bump version to 2.2.0

examples/main/package.json, yarn.lock
=> [*] fix(yarn.lock) update and dedup

examples/storybook/package.json, yarn.lock
Reverts wix-incubator/rich-content#1659
=> Revert "build(deps): bump lint-staged from 7.3.0 to 10.4.2"

packages/plugin-commons/web/src/Components/ColorPicker/ColorPicker.jsx, packages/plugin-commons/web/statics/styles/color-picker.scss
=> [color-picker] support transparent color

packages/plugin-button/web/src/components/settings-component.jsx
=> [button] settings component refactor

CHANGELOG.md, packages/plugin-emoji/web/src/toolbar/emojiPreviewModal.jsx, packages/plugin-giphy/web/src/toolbar/giphySelector.jsx
- `giphy`
- a11y improved in popup
- `emoji`
- a11y improved in popup
=> Fix a11y in emoji and giphy popups

CHANGELOG.md, examples/main/shared/viewer/Viewer.jsx, examples/main/shared/viewer/ViewerPlugins.jsx, packages/plugin-image/web/src/image-viewer.jsx, packages/plugin-link/web/src/LinkViewer.jsx, packages/viewer/web/src/getPluginViewers.jsx
=> [anchor] add optional siteUrl in config (SEO)

CHANGELOG.md, packages/plugin-social-polls/web/src/components/image-upload/ImageUpload.jsx, packages/plugin-social-polls/web/src/components/image-upload/image-upload.scss, packages/plugin-social-polls/web/src/components/poll-header/PollHeader.jsx, packages/plugin-social-polls/web/src/components/text-field/TextField.jsx
Makes possible to create & edit social polls without using a mouse
=> social polls editor a11y

.github/workflows/tests.yml
=> fix notifyOnSlack git action

.github/workflows/release.yml
=> release GitHub action added

README.md
=> gif update

.github/workflows/tests.yml, e2e/cypress/support/commands.js, package.json, packages/viewer/web/src/RichContentViewer.tsx, yarn.lock
=> [package.json] update cypress to 6

packages/common/web/statics/schemas/vertical-embed.schema.json
=> [vertical-embed]fix: plugin scheme

.github/workflows/actions.yml, .github/workflows/bundleSize.yml, .github/workflows/pr_creation.yml, .github/workflows/release.yml, .github/workflows/tests.yml, package.json
=> Welcome to midgard

packages/plugin-accordion/web/src/mobileNativeLoader.js, packages/plugin-button/web/src/mobileNativeLoader.js, packages/plugin-sound-cloud/web/src/mobileNativeLoader.js
=> [mobileNativeLoader]

docs/docusaurus.config.js
=> [docs] algolia search integrated

README.md, docs/docs/intro.mdx, docs/docs/plugins_api/LinkPlugin.mdx, docs/docs/plugins_api/PluginCustomization.md, docs/docs/rce_api/ToolbarCustomization.mdx, docs/docs/ricos/Preview.mdx, docs/docs/ricos/migrations/migrating-to-v7.md, docs/docs/ricos/migrations/migrating-to-v8.mdx, docs/docs/ricos/ricos-api.mdx, docs/docusaurus.config.js, docs/src/pages/index.js
=> [docs] links update wix-incubator => wix

docs/docs/dev/bundle_analyzer.md, docs/docs/dev/plugin.md, docs/docs/dev/release.md, docs/docs/dev/testing.md, docs/docs/dev/theme.md, docs/docs/ricos/adsense.md, docs/docs/ricos/keyboard_shortcuts.md, docs/docs/ricos/media_handling.md, docs/docs/ricos/mobile_support.md, docs/docusaurus.config.js, docs/sidebars.js
=> [docs] wiki pages moved to docs

CHANGELOG.md, packages/editor/web/src/RichContentEditor/RichContentEditor.tsx, packages/editor/web/src/RichContentEditor/Toolbars/StaticToolbar/MoreButton.js, packages/editor/web/src/RichContentEditor/Toolbars/StaticToolbar/StaticToolbar.jsx, packages/editor/web/statics/styles/static-toolbar-more-button.scss, packages/plugin-commons/web/src/Base/createBaseInsertPluginButton.jsx, packages/plugin-commons/web/statics/styles/toolbar-button.scss
=> [inner-rce] disable FooterToolbar when innerRCE in focus

packages/plugin-table/web/src/table-component.jsx
=> [table]fix: remove rows and cols selection while edit

packages/plugin-table/web/src/components/Rows.js, packages/plugin-table/web/src/table-component.jsx, packages/plugin-table/web/statics/styles/rows.scss
=> [table]fix: reorder row to be first

packages/plugin-table/web/src/components/Resizer.js, packages/plugin-table/web/src/components/Rows.js, packages/plugin-table/web/statics/styles/resizer.scss
=> [table]fix: disable style of first row resizer

packages/plugin-table/web/src/components/CellRenderer.js
=> [table]fix: align cell content on editing

packages/plugin-table/web/src/components/CellRenderer.js
=> [table-plugin]fix: cell borders display on selection mode

packages/plugin-table/web/src/table-component.jsx, packages/toolbars/web/src/Toolbar/ButtonComponents/ColorPickerButton.jsx
=> [table] fix: press backspace on color-picker input

e2e/tests/settings.js
=> disable facebook-video test

CHANGELOG.md, packages/plugin-unsupported-blocks/web/package.json
=> [unsupported-blocks] feat: update plugin to be public

packages/viewer/web/statics/rich-content-viewer.scss
=> [viewer]fix: remove viewer BG color

packages/plugin-table/web/src/TableToolbar/CellFormattingButtonProps.js
=> [table] fix border default color + remove transparent from borders

packages/plugin-table/web/src/components/TableRenderer.js
=> [table] fix: resize cols bug

packages/editor/web/statics/styles/inline-toolbar.rtlignore.scss
=> [editor] fix: inline toolbar ui bug

packages/plugin-table/web/src/components/Rows.js, packages/plugin-table/web/src/domain/table.js, packages/plugin-table/web/src/table-component.jsx
=> [table] fix row resizer min height

packages/editor/web/statics/styles/static-toolbar.scss
=> [mobile editor]fix: static toolbar z index

packages/plugin-table/web/src/components/CellRenderer.js, packages/plugin-table/web/statics/styles/cell.scss
=> [table]fix: selection style on cells with bg color

packages/plugin-table/web/statics/styles/drag-and-drop.scss
=> [table] remove unnecessary border

packages/plugin-table/web/src/TableToolbar/CellFormattingButtonProps.js, packages/plugin-table/web/src/domain/table.js
=> [table]fix: reset to default border around

packages/plugin-table/web/src/TableToolbar/CellFormattingButtonProps.js
=> [table] fix: bg and border color (color picker add new color button)

packages/plugin-table/web/src/components/CellRenderer.js, packages/plugin-table/web/statics/styles/cell.scss
=> [table]fix: cell aligment and borders bug

packages/plugin-table/web/src/components/CellRenderer.js, packages/plugin-table/web/statics/styles/cell.scss
=> [table]fix: selection bg style

packages/plugin-table/web/src/components/CellRenderer.js, packages/plugin-table/web/statics/styles/cell.scss
=> [table]fix: selected bordeers

packages/plugin-table/web/package.json, yarn.lock
=> [table] fix: selection range of cells with shift key

CHANGELOG.md, packages/plugin-unsupported-blocks/web/statics/styles/unsupported-blocks.scss
=> [unsupported-blocks] fix: bg color update

packages/plugin-table/web/src/components/TableRenderer.js, packages/plugin-table/web/src/table-viewer.jsx
=> [table]fix: colGroup set width attribute

packages/plugin-commons/web/src/Base/createBasePlugin.ts, packages/plugin-commons/web/src/Base/toolbars/createAtomicPluginToolbar.jsx, packages/plugin-commons/web/src/Base/toolbars/toolbarUtils.js, packages/plugin-commons/web/statics/styles/plugin-toolbar.scss
=> [table] fix atomic plugins toolbars in table

e2e/tests/__snapshots__/text.e2e.js.snap, e2e/tests/fixtures/non-text-only-blocks.json
=> [e2e] fix indent test

examples/main/shared/RichContentApp.tsx, examples/main/src/ExampleApp.tsx, examples/storybook/stories/Ricos/RicosBasicUsage.tsx, examples/storybook/stories/Ricos/RicosStaticToolbar.tsx, packages/editor/web/src/RichContentEditor/RichContentEditor.tsx, packages/editor/web/src/is-content-changed.ts, packages/ricos-common/web/src/RicosTypes.ts, packages/ricos-content/web/src/index.ts, packages/ricos-editor/web/src/RicosEditor.tsx, packages/ricos-editor/web/src/utils/editorUtils.ts
=> Revert "fix content traits"

packages/plugin-commons/web/src/Base/toolbars/createAtomicPluginToolbar.jsx, packages/plugin-commons/web/src/Base/toolbars/toolbarUtils.js
=> [table] improve atomic plugins toolbars in table

packages/editor/web/src/RichContentEditor/InnerRCE.jsx
=> [inner-rce] fix: improve toolbars appearance in table plugin

packages/plugin-commons/web/src/Base/createBaseInsertPluginButton.jsx
=> [inner-rce] fix: disable footer in inner-rce

packages/plugin-table/web/src/components/CellRenderer.js
=> [table] fix: cell height on edit

packages/plugin-table/web/src/TableToolbar/ContextMenuButtonProps.js, packages/plugin-table/web/src/domain/table.js, packages/plugin-table/web/src/domain/tableDataUtil.js, packages/plugin-table/web/src/table-component.jsx, packages/plugin-table/web/src/test/__snapshots__/table.spec.js.snap, packages/plugin-table/web/src/test/table.spec.js
=> fix distribute rows

packages/plugin-table/web/src/TableToolbar/ContextMenuButtonProps.js, packages/plugin-table/web/src/TableToolbar/TableToolbar.js, packages/plugin-table/web/src/table-component.jsx
=> [table]fix: remove selection after distribute

packages/plugin-table/web/src/components/Columns.js, packages/plugin-table/web/src/components/Resizer.js, packages/plugin-table/web/src/components/TableRenderer.js, packages/plugin-table/web/src/table-component.jsx, packages/plugin-table/web/src/table-viewer.jsx
=> [table]fix: resize table overflow width

packages/editor/web/src/RichContentEditor/RichContentEditor.tsx, packages/viewer/web/src/RichContentViewer.tsx, packages/viewer/web/src/getPluginViewers.jsx
=> [inner-rce] disable inner-rce bi events

packages/plugin-table/web/src/components/CellRenderer.js
=> [table]fix: remove select all content on selected on cells on mobile

packages/plugin-table/web/src/components/CellRenderer.js, packages/plugin-table/web/src/toolbar/tableSettingsModal.js, packages/plugin-table/web/statics/styles/table-settings-modal.scss
=> [table]fix: focus on table modal elements & fix v key bug

CHANGELOG.md, packages/editor/web/src/RichContentEditor/Toolbars/SideToolbar/PluginMenuPluginsSection.js, packages/editor/web/statics/styles/side-toolbar-panel.scss, packages/plugin-commons/web/src/Base/createBaseInsertPluginButton.jsx
=> [editor]fix: horizontal side toolbar theme

packages/plugin-table/web/src/components/CellRenderer.js, packages/plugin-table/web/src/table-component.jsx
=> [table]fix: resize crash bug

packages/plugin-table/web/src/domain/tableDataUtil.js
=> [table]fix: cell min width on mobile

packages/plugin-headings/web/src/toolbar/createToolbar.tsx
=> fix external headings

packages/plugin-table/web/src/components/TableRenderer.js
=> [table] fix: remove resize event listener

examples/storybook/stories/Ricos/RicosContentStory.tsx, packages/ricos-common/web/src/RicosEngine.tsx, packages/ricos-common/web/src/RicosTypes.ts, packages/ricos-editor/web/src/modals/EditorModalProvider.tsx
=> Ricos: modal events for internal modal handling

packages/plugin-table/web/src/components/CellRenderer.js, packages/plugin-table/web/statics/styles/table-component.scss
=> [table]fix: safari user-selection & pate fix

packages/plugin-commons/web/src/Base/createBaseInsertPluginButton.jsx
=> [editor]fix: plugins insert buttons with type file hover style fix

packages/editor/web/src/RichContentEditor/RichContentEditor.tsx, packages/ricos-common/web/src/localeStrategy/localeStrategy.ts, packages/ricos-common/web/src/pluginsStrategy/pluginsStrategy.ts, packages/ricos-common/web/src/previewStrategy/previewStrategy.ts, packages/ricos-common/web/src/themeStrategy/themeStrategy.tsx
=> don't log empty experiments

packages/plugin-commons/web/src/Utils/generateInsertPluginButtonProps.ts
=> blur hack for giphy (#1110) revert

packages/editor-common/web/src/consts.ts, packages/plugin-table/web/src/components/CellRenderer.js, packages/plugin-table/web/src/table-component.jsx
=> [table] keyboard commands

e2e/tests/table.e2e.js
=> [table]test refactor

packages/common/web/statics/locale/messages_en.json, packages/editor-common/web/statics/locale/messages_en.json, packages/plugin-table/web/src/TableToolbar/CellFormattingButtonProps.js
=> [table] fix: translations

packages/plugin-link/web/src/toolbar/TextLinkButton.jsx
=> fix static toolbar link modal styles

packages/plugin-table/web/src/components/CellRenderer.js, packages/plugin-table/web/src/table-component.jsx
=> [table]fix: shortcut undo

packages/ricos-editor/web/src/utils/editorUtils.ts
=> contentTraits expose isLastChangeEdit

packages/plugin-table/web/src/TableToolbar/TableToolbar.js, packages/plugin-table/web/src/table-component.jsx, packages/toolbars/web/src/Toolbar/ButtonComponents/ContextMenu.js, packages/toolbars/web/src/Toolbar/ToolbarButton.scss, packages/toolbars/web/src/Toolbar/ToolbarContainer.jsx
=> [table] add shortcuts to table toolbars

CHANGELOG.md, packages/plugin-commons/web/src/Utils/generateInsertPluginButtonProps.ts
=> [ricos-editor] fix(callbacks): onPluginAddStep

packages/plugin-table/web/src/components/CellRenderer.js
=> [table] fix: disable scrolling horizontal with arrows left and right

packages/editor-common/web/statics/styles/general.scss, packages/plugin-commons/web/src/Base/createBaseComponent.jsx
=> [table]fix: show horizontal scrollbar only on focus

.github/workflows/release.yml
=> [scripts] feat(release) repository dispatch ricos update on wix-ricos

packages/plugin-table/web/src/TableToolbar/ContextMenuButtonProps.js
=> [table]fix: display distrbute option in context menu on right cases

packages/plugin-table/web/src/toolbar/tableSettingsModal.js
=> [table]fix: limit cells creation number

CHANGELOG.md, packages/plugin-image/web/src/image-viewer.jsx
=> [image plugin] thumbnail quality by experiment

packages/plugin-table/web/src/TableToolbar/TableToolbar.js, packages/plugin-table/web/src/table-component.jsx
=> [table]fix: drag preview position on scroll

packages/plugin-table/web/src/table-component.jsx
=> [table] update table toolbar shortcut

website/docs/plugins_api/HtmlPlugin.mdx
=> [docs] add adsense to html docs

examples/main/shared/editor/EditorPlugins.tsx, packages/plugin-text-color/web/src/toolbar/BaseTextColor.jsx, website/docs/plugins_api/TextColorAndHighlightPlugins.mdx
=> [color-picker] feat : Add picker positioning override setting

packages/plugin-table/web/src/TableToolbar/ContextMenuButtonProps.js
=> [table]fix: tooltips on disabled buttons

packages/plugin-table/web/src/toolbar/tableSettingsModal.js, packages/plugin-table/web/statics/styles/table-settings-modal.scss
=> [table]fix: modal elements accessibility

packages/plugin-table/web/src/domain/table.js, packages/plugin-table/web/src/table-viewer.jsx
=> [table]fix: delete columns crash

CHANGELOG.md, e2e/cypress/support/commands.js, e2e/tests/rendering.e2e.js, e2e/tests/renderingSsr.e2e.js, examples/main/shared/theme/theme.ts, packages/ricos-viewer/web/src/RicosViewer.tsx
=> @oded-soffrin [viewer] optimization(translations): skip redundant remount

packages/editor/web/src/RichContentEditor/RichContentEditor.tsx
=> [editor]fix: inner rce background color

examples/storybook/stories/TestCase/ImagePluginQualityPreload.tsx, packages/plugin-image/web/src/image-viewer.tsx
=> [image-viewer](fix): fix useSrcSet

packages/plugin-table/web/src/table-component.jsx
=> [table]fix: drag and drop preview position

packages/editor/web/src/RichContentEditor/InnerRCE.jsx
=> [inner-rce] change default plugins logic

website/docs/plugins_api/TablePlugin.mdx, website/sidebars.js
=> [table] add documantation

packages/plugin-table/web/package.json, yarn.lock
=> [table]fix: tab key go out from cell edit and navigate to the next one

packages/plugin-sound-cloud/web/src/createSoundCloudPlugin.ts
=> [sound-cloud] deprecation warning

packages/editor/web/src/RichContentEditor/InnerRCE.jsx, packages/plugin-table/web/src/components/CellRenderer.js, packages/plugin-table/web/src/table-component.jsx, packages/plugin-table/web/src/table-viewer.jsx, packages/plugin-table/web/statics/styles/cell.scss
=> [table]fix: select all selected cell content

CHANGELOG.md, packages/plugin-table/web/src/components/CellRenderer.js, packages/plugin-table/web/statics/styles/cell.scss
=> [table]fix: pointer events

CHANGELOG.md, packages/plugin-headings/web/src/toolbar/HeadingButton.jsx, packages/plugin-headings/web/src/types.ts, website/docs/plugins_api/HeadingsPlugin.mdx, website/sidebars.js
=> [heading]fix: triple click display the right heading

packages/common/web/statics/styles/general.rtlignore.scss, packages/viewer/web/src/RichContentViewer.tsx, packages/viewer/web/src/getPluginViewers.jsx
=> [table] fix: atomic plugis size in viewer

CHANGELOG.md, packages/editor/web/src/RichContentEditor/Toolbars/SideToolbar/utils.js, packages/plugin-accordion/web/src/toolbar/insert-buttons.ts, packages/plugin-button/web/src/toolbar/insert-buttons.tsx, packages/plugin-code-block/web/src/toolbar/createToolbar.ts, packages/plugin-map/web/src/toolbar/insert-buttons.tsx, packages/plugin-social-polls/web/src/toolbar/createToolbar.ts, packages/plugin-table/web/src/toolbar/insert-buttons.tsx
=> [plugin-menu]fix: add plugins to advanced section

packages/plugin-table/web/src/components/CellRenderer.js, packages/plugin-table/web/statics/styles/cell.scss
=> [table]fix: edit cell on mobile

website/docs/plugins_api/LinkPreviewPlugin.mdx, website/docs/plugins_api/TablePlugin.mdx, website/src/css/custom.scss
=> [docs] table style

packages/editor-common/web/src/Utils/overflowUtils.ts, packages/editor/web/src/RichContentEditor/RichContentEditor.tsx
=> [table] fix: side toolbar + context menu overflow logic

packages/plugin-table/web/src/components/CellRenderer.js
=> [table]fix: ctrl+a command on cell fix

packages/plugin-table/web/src/table-component.jsx
=> [table]fix: select rows/cols shortcuts

packages/common/web/src/types/buttonTypes.ts, packages/common/web/src/types/toolbarSettingsTypes.ts, packages/editor-common/web/src/Components/InlineToolbarButton.tsx, packages/plugin-image/web/src/image-viewer.tsx
=> wix-data fixes

packages/plugin-commons/web/statics/styles/custom-color-picker.scss, packages/plugin-link/web/src/toolbar/TextLinkButton.jsx
=> wix-data issues

packages/plugin-image/web/src/image-viewer.tsx
=> [image-viewer](perf): skip image optimization for mobile and png files

packages/plugin-image/web/src/image-viewer.tsx
=> image performance fix for png

packages/plugin-headings/web/src/toolbar/HeadingButton.jsx, packages/plugin-line-spacing/web/src/toolbar/LineSpacingButton.jsx, packages/plugin-text-color/web/src/toolbar/BaseTextColor.jsx
=> inlinePopups flag

packages/editor-common/web/statics/styles/inline-toolbar-button.scss, packages/editor/web/statics/styles/text-static-toolbar.scss, packages/plugin-line-spacing/web/statics/styles/styles.scss, packages/plugin-text-color/web/statics/styles/text-color-modal.scss
=> inline popup styles fixed

packages/plugin-commons/web/src/Base/toolbars/createAtomicPluginToolbar.jsx, packages/plugin-commons/web/statics/styles/plugin-toolbar.scss
=> plugin-toolbar: add MARGIN_LEFT

packages/editor/web/src/RichContentEditor/Toolbars/TextLinkModal.jsx
=> TextLinkModal supports image link

CHANGELOG.md, packages/common/web/src/types/pluginTypes.ts
=> editorCommands - allow any data when using draft types

packages/plugin-vertical-embed/web/src/components/vertical-embed-component.jsx
=> [plugin vertical embed] add onclick viewer bi

packages/plugin-map/web/src/MapViewer.jsx
=> [map-plugin] add on click viewer bi

packages/plugin-button/web/src/components/button-component.jsx, packages/plugin-button/web/src/components/button-viewer.jsx
=> [button-plugin] add on click viewer bi

packages/plugin-accordion/web/src/accordion-viewer.jsx, packages/plugin-accordion/web/src/components/AccordionPair.jsx, packages/plugin-accordion/web/src/components/AccordionPairs.jsx
=> [accordion-plugin] add collapse/expand viewer bi event

packages/plugin-file-upload/web/src/file-upload-viewer.jsx
=> [file-upload] add file download bi

packages/plugin-link-preview/web/src/LinkPreviewViewer.jsx
=> [link-preview] add on click bi

examples/main/shared/editor/EditorPlugins.tsx, packages/common/web/src/types/toolbarSettingsTypes.ts, packages/editor/web/src/RichContentEditor/Toolbars/SideToolbar/AddPluginFloatingToolbar.jsx, packages/editor/web/src/RichContentEditor/Toolbars/SideToolbar/createSideToolbar.jsx, packages/editor/web/src/RichContentEditor/Toolbars/createEditorToolbars.ts
=> [editor]feat: add on click for plus button

packages/plugin-commons/web/src/Base/createBaseComponent.jsx
=> componentLink removed rather set to null

packages/editor/web/src/RichContentEditor/RichContentEditor.tsx, packages/plugin-commons/web/src/Base/createBasePlugin.ts, packages/plugin-commons/web/src/Base/toolbars/createAtomicPluginToolbar.jsx
=> [editor]fix: hide inline toolbar when click outside the editor

CHANGELOG.md, packages/plugin-html/web/src/htmlIframeSrc.ts
=> [html]fix: iframe width bug fix

e2e/tests/__snapshots__/plugins.e2e.js.snap, e2e/tests/fixtures/migration-content.json, e2e/tests/fixtures/plain-text-content.json, e2e/tests/fixtures/storybook-example-app.json, e2e/tests/fixtures/vertical-embed.json, packages/plugin-vertical-embed/web/src/constants.ts, packages/plugin-vertical-embed/web/src/createVerticalEmbedPlugin.ts, packages/plugin-vertical-embed/web/src/editor.ts, packages/plugin-vertical-embed/web/src/toolbar/insert-buttons.tsx, packages/plugin-vertical-embed/web/src/viewer.ts, packages/ricos-content/web/statics/json/migratedFixtures/migration-content.json, packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_vertical_embed.proto, packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_vertical_embed.proto
=> [vertical-embed] add new ricos schema

.github/workflows/actions.yml, .github/workflows/tests.yml
=> limit github actions

CHANGELOG.md, package.json, yarn.lock
=> [e2e] cypress 7

scripts/deployment/deployUtils.js
=> [github actions] fix deploy examples

CHANGELOG.md, e2e/tests/fixtures/storybook-example-app.json, packages/plugin-image/web/src/InPluginInput.tsx, packages/plugin-image/web/src/image-viewer.tsx, packages/plugin-image/web/statics/styles/image-viewer.rtlignore.scss, packages/plugin-image/web/statics/styles/in-plugin-input.scss
Plugin Image's caption wasn't wired to Ricos Theme.
Goals:
- Wire image-caption to regular paragraph styling
- Wire image-caption to link styling when necessary
=> [plugin-image] fix(caption): theme wiring

.github/workflows/tests.yml, applitools.config.js
=> [e2e] fix applitools branch name

packages/viewer/web/src/RichContentViewer.tsx
=> [spoiler plugin] move spoiler bi to wix-ricos

e2e/tests/media.e2e.js
=> [e2e] fix fullscreen test

CHANGELOG.md, packages/text-selection-toolbar/web/src/TextSelectionToolbar.tsx
=> [text-selection-toolbar]fix: toolbar position with scroll

CHANGELOG.md, packages/plugin-file-upload/web/src/file-upload-viewer.jsx
=> [file-upload] fix: restore download key

packages/editor-common/web/src/index.ts, packages/editor/web/src/RichContentEditor/RichContentEditor.tsx, packages/ricos-editor/web/src/utils/editorUtils.ts
=> null content defaults to empty for traits calculation

CHANGELOG.md, packages/plugin-commons/web/src/Base/toolbars/createInlinePluginToolbar.jsx
=> [link-toolbar] fix: update link toolbar when moving from link to link

examples/main/shared/editor/EditorPlugins.tsx, packages/common/web/src/types/pluginTypes.ts, packages/plugin-commons/web/src/Base/buttons/BlockLinkButton.jsx, packages/plugin-link/web/src/toolbar/TextLinkButton.jsx
=> link modal opened with external modal

examples/storybook/package.json, examples/storybook/stories/styles.global.scss, packages/ricos-viewer/web/src/TextSelectionToolbar.tsx, packages/ricos-viewer/web/src/textSelectionToolbarStyles.css
=> [text-selection-toolbar]fix: import styles from ricos viewer

packages/ricos-content/web/src/converters/proseMirror/toProseMirror/__tests__/migrationContentProse.json, packages/ricos-content/web/statics/json/migratedFixtures/migration-content.json
=> update migrationContent files

packages/plugin-button/web/src/components/button-component.jsx, packages/plugin-button/web/src/components/design-component.jsx, packages/plugin-button/web/src/toolbar/buttonInputModal.jsx
=> [plugin-button] fix: edge cases on save colors in componentData logic

CHANGELOG.md, packages/template-atomic-plugin/web/package.json, packages/template-atomic-plugin/web/src/__mocks__/fileMock.ts, packages/template-atomic-plugin/web/src/__mocks__/styleMock.ts, packages/template-atomic-plugin/web/src/tests/yourDpluginDname-viewer.spec.tsx, packages/template-atomic-plugin/web/src/yourDpluginDname-component.tsx, packages/template-atomic-plugin/web/src/yourDpluginDname-viewer.tsx, packages/template-atomic-plugin/web/statics/styles/yourDpluginDname.scss
- `yarn generatePlugin` resulted with several lint issues that are now fixed
- viewer component is now a functional component
=> [template-atomic-plugin] polish: lint & FC viewer

e2e/tests/fixtures/storybook-example-app.json
=> [storybook + e2e] improve: button coverage

packages/ricos-content/web/lib/extract-media.ts, packages/ricos-content/web/libs/extract-media/package.json, packages/ricos-content/web/src/converters/extract-media.spec.ts, packages/ricos-content/web/src/converters/extract-media.ts, packages/ricos-content/web/src/preview/ContentStateAnalyzer/ContentStateMetadata.spec.ts, packages/ricos-content/web/src/preview/ContentStateAnalyzer/extractEntityData.ts, packages/ricos-content/web/src/preview/ContentStateBuilder/ContentStateBuilder.spec.ts, packages/ricos-content/web/src/preview/ContentStateBuilder/mergeEntityData.ts, packages/ricos-content/web/src/preview/Interactions/interaction-utils.spec.ts
=> media extractor for SEO

packages/plugin-button/web/src/components/button-viewer.tsx
=> [button] fix: link data rendered in action button

website/docs/content_api/extract_media.md, website/sidebars.js
=> [docs] extract_media

CHANGELOG.md, packages/common/web/src/draftDecorators/createJustificationFixDecorator.tsx
=> [common] fix double link when text is justified on safari/firefox

website/docs/plugins_api/ButtonPlugin.mdx
=> [docs] update plugin-button docs

CHANGELOG.md, packages/ui-components/web/package.json
=> [ui-components] refactor: publish package

CHANGELOG.md, packages/editor-common/web/src/Components/LinkComponents/LinkPanel.jsx
=> [link] fix: hide sponsored cb in link panel by default

CHANGELOG.md, packages/common/web/src/draftDecorators/createJustificationFixDecorator.tsx
=> [common] disable justification fix on SSR

rollup.externals.ts
=> [rollup] add toolbar package into externals

packages/ricos-content/web/lib/extract.ts, packages/ricos-content/web/lib/modify.ts, packages/ricos-content/web/libs/extract/package.json, packages/ricos-content/web/libs/modify/package.json
=> extract, modify added to libs

packages/editor-common/web/src/Modals/RichContentModal.tsx
=> [editor]fix: render wrapper modal fix

website/docs/plugins_api/SpoilerPlugin.mdx, website/package.json, website/yarn.lock
=> [spoilr] add docs

packages/ricos-editor/web/src/RicosEditor.tsx
=> [ricos-editor] refactor(RicosEditor) tiptapApi and editorRef separated

examples/storybook/stories/ContentAPI/ContentBuilder.tsx, examples/storybook/stories/ContentAPI/types.ts, packages/ricos-content/web/src/RicosContentAPI/RicosContentBuilder.ts, packages/ricos-content/web/src/RicosContentAPI/builder-utils.spec.ts, packages/ricos-content/web/src/RicosContentAPI/builder-utils.ts, packages/ricos-content/web/src/RicosContentAPI/modify.ts, packages/ricos-content/web/src/fp-utils.ts, packages/tiptap-editor/web/src/TiptapEditor.tsx
=> lodash/pf replaced with fp-ts

e2e/tests/fixtures/linkPreview.json, examples/main/shared/utils/linkPreviewUtil.js, packages/plugin-link-preview/web/lib/utils.ts, packages/plugin-link-preview/web/src/LinkPreviewViewer.jsx
=> [link-preview] support link preview without image

packages/plugin-commons/web/src/Base/toolbars/createAtomicPluginToolbar.jsx, packages/plugin-gallery/web/src/components/gallery-settings-modal.js, packages/plugin-gallery/web/src/toolbar/inline-buttons.tsx, packages/plugin-image/web/src/toolbar/image-settings.js, packages/plugin-image/web/src/toolbar/inline-buttons.tsx, packages/plugin-video/web/src/toolbar/video-settings.tsx
=> [spoiler-plugin] fix: remove spoiler toggle from media settings modal

rollup.plugins.ts
=> tiptap to es5

website/docs/plugins_api/SpoilerPlugin.mdx
=> [docs] fix spoiler docs

examples/main/shared/editor/EditorPlugins.tsx
=> [example-app] inner rce's consumption

CHANGELOG.md, packages/plugin-collapsible-list/web/src/createCollapsibleListPlugin.ts, packages/plugin-table/web/src/createTablePlugin.ts
=> [table,collapsible] add localeContent support

packages/plugin-link-preview/web/statics/styles/link-preview.scss
=> [link-preview] url color wiring

CHANGELOG.md, packages/editor/web/src/RichContentEditor/RichContentEditor.tsx, packages/viewer/web/src/RichContentViewer.tsx
=> [*] console.error for errors caught in editor/viewer

e2e/tests/fixtures/migration-content.json, packages/ricos-content/web/src/converters/html/fromHtml/__tests__/richTextContent.json, packages/ricos-content/web/src/converters/plainText/fromPlainText/plainTextContent.json, packages/ricos-content/web/src/converters/tiptap/toTiptap/__tests__/migrationContentTiptap.json, packages/ricos-content/web/statics/json/migratedFixtures/migration-content.json
=> [ricos-content] update migration content & baselines

packages/ricos-content/web/src/converters/draft/fromDraft/convertRicosPluginData.ts, packages/ricos-content/web/src/converters/draft/toDraft/convertDraftPluginData.ts, packages/ricos-content/web/src/converters/html/fromHtml/__tests__/richTextContent.json, packages/ricos-content/web/src/converters/plainText/fromPlainText/plainTextContent.json, packages/ricos-content/web/src/converters/tiptap/toTiptap/__tests__/migrationContentTiptap.json, packages/ricos-content/web/statics/json/migratedFixtures/migration-content.json, packages/ricos-editor/web/src/utils/editorCommandsTestsUtil.ts, packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_divider.proto, packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_divider.proto
=> [divider] final schema

packages/ricos-content/web/src/converters/draft/fromDraft/convertRicosPluginData.ts, packages/ricos-content/web/src/converters/draft/toDraft/convertDraftPluginData.ts, packages/ricos-content/web/src/converters/plainText/fromPlainText/plainTextContent.json, packages/ricos-content/web/src/converters/plainText/toPlainText/complexPlainText.ts, packages/ricos-content/web/src/converters/plainText/toPlainText/convertNodes.ts, packages/ricos-content/web/src/converters/plainText/toPlainText/toPlainText.ts, packages/ricos-content/web/src/converters/tiptap/toTiptap/__tests__/migrationContentTiptap.json, packages/ricos-content/web/statics/json/migratedFixtures/migration-content.json, packages/ricos-schema/web/src/generated/proto/wix/rich_content/v1/plugin_video.proto, packages/ricos-schema/web/src/main/proto/wix/rich_content/v1/plugin_video.proto
=> [ricos-schema] add title to video schema

packages/common/web/lib/Tooltip.tsx, packages/common/web/src/Utils/contentAnalytics.ts, packages/editor-common/web/src/Utils/draftUtils.ts, packages/ricos-editor/web/src/RicosEditor.tsx
=> Lazy loaded tooltip: added Suspense

packages/ricos-editor/web/src/RicosEditor.tsx, packages/tiptap-editor/web/package.json, yarn.lock
=> remove tiptap

packages/ricos-content/web/lib/tiptap.ts, packages/ricos-content/web/libs/tiptap/package.json, packages/ricos-editor/web/src/RicosEditor.tsx, packages/tiptap-editor/web/src/TiptapEditor.tsx, packages/tiptap-editor/web/src/components/BaseComponent/BaseComponent.tsx, packages/tiptap-editor/web/src/tiptap-extensions.ts
=> fix es6 issue

CHANGELOG.md, packages/common/web/lib/Tooltip.tsx
=> [common] tooltip doesn't hide + preload tooltip

packages/ricos-content/web/src/converters/extract-media.spec.ts, packages/ricos-content/web/src/converters/extract-media.ts, packages/ricos-content/web/src/converters/plainText/fromPlainText/plainTextContent.json, packages/ricos-content/web/src/converters/plainText/toPlainText/complexPlainText.ts, packages/ricos-content/web/src/converters/plainText/toPlainText/convertNodes.ts
=> getImgSrc removed from converters

CHANGELOG.md, packages/common/web/lib/Tooltip.tsx
=> [common] fix tooltip in ssr - regression from 8.46.13

CHANGELOG.md, packages/plugin-html/web/src/IframeUrl.tsx
=> [html] allow popups from embed

CHANGELOG.md, packages/common/web/lib/Tooltip.tsx
=> [common] fix tooltip not disappearing

packages/plugin-table/web/src/table-component.jsx
=> [table]fix: tables componentData from store override

packages/editor/web/src/RichContentEditor/RichContentEditor.tsx, packages/ricos-editor/web/src/RicosEditor.tsx, packages/viewer/web/src/RichContentViewer.tsx
=> fix webpackChunkName magic comments

CHANGELOG.md, packages/editor-common/web/src/Components/LinkComponents/LinkPanelDropdown.jsx, rollup.externals.ts
=> [*] make downshift external

CHANGELOG.md, packages/viewer/web/src/utils/convertContentState.tsx
https://jira.wixpress.com/browse/RICH-515
=> [viewer] add presentation role to BR in order to skip on screen readers

CHANGELOG.md, packages/toolbars-new/web/src/Toolbar/ToolbarNew.scss
=> [toolbars-new] fix: mobile style colorpicker modal

packages/tiptap-editor/web/src/components/RichContentAdapter/RichContentAdapter.tsx, packages/tiptap-editor/web/src/core/commands/deleteNode.ts, packages/tiptap-editor/web/src/core/extensions/commands.ts
=> [tiptap] add deleteNode command

packages/ricos-content/web/src/converters/draft/fromDraft/convertRicosPluginData.ts
=> [ricos-content] set default image item type in gallery item convertor

packages/ricos-editor/web/src/RicosEditor.tsx, packages/tiptap-editor/web/src/components/RicosTiptapEditor/RicosTiptapEditor.tsx, packages/tiptap-editor/web/src/components/RicosTiptapEditor/core-configs.ts, packages/tiptap-editor/web/src/index.ts, packages/tiptap-editor/web/src/types.ts
=>  fixed on atomic block focus

packages/ricos-editor/web/src/RicosEditor.tsx, packages/tiptap-editor/web/src/components/RichContentAdapter/RichContentAdapter.tsx, packages/tiptap-editor/web/src/components/RicosTiptapEditor/RicosTiptapEditor.tsx
=> Fix tiptap focus bugs

packages/plugin-gallery/web/src/tiptap/tiptap.ts, packages/plugin-image/web/src/tiptap/tiptap.ts, packages/ricos-editor/web/src/RicosEditor.tsx, packages/tiptap-editor/web/src/components/RicosTiptapEditor/RicosTiptapEditor.tsx, packages/tiptap-editor/web/src/components/RicosTiptapEditor/core-configs.ts, packages/tiptap-editor/web/src/core/extensions/commands.ts, packages/tiptap-editor/web/src/extensions/extension-unique-id/index.ts, packages/tiptap-editor/web/src/extensions/extension-unique-id/unique-id.tsx, packages/tiptap-editor/web/src/tiptap-extensions.ts, packages/tiptap-editor/web/src/types.ts
=> [tiptap]: unique-id extension & fix selection callbback

packages/common/web/src/types/pluginTypes.ts, packages/plugin-file-upload/web/src/editor.ts, packages/plugin-file-upload/web/src/types.ts, packages/plugin-gallery/web/src/editor.ts, packages/plugin-image/web/src/editor.ts, packages/plugin-image/web/src/types.ts, packages/plugin-video/web/src/editor.ts, packages/ricos-editor/web/src/RicosEditor.tsx
=> [internal] add configFixer functionality

packages/common/web/statics/schemas/content-state.schema.json, packages/common/web/statics/schemas/plugin-collapsible-list.schema.json, packages/common/web/statics/schemas/plugin-gallery.schema.json, packages/common/web/statics/schemas/plugin-html.schema.json, packages/common/web/statics/schemas/plugin-image.schema.json, packages/common/web/statics/schemas/vertical-embed.schema.json
=> [schema]fix: cleanup errors

packages/tiptap-editor/web/src/components/RichContentAdapter/RichContentAdapter.tsx
=> [editor-commands]fix: set editor focus to decoration commands

packages/tiptap-editor/web/src/extensions/extension-unique-id/unique-id.tsx
=> [tiptap]fix: node unique id validation

packages/tiptap-editor/web/src/extensions/extension-styles/index.tsx
=> [tiptap]fix: node focus style

packages/plugin-file-upload/web/src/tiptap/tiptap.ts, packages/tiptap-editor/web/src/core/commands/updateNodeById.ts
=> [tiptap]fix: file upload loading state

bundle-analyzer/bundlesSizesBaseline.json, e2e/cypress/support/commands.ts, packages/common/web/src/Utils/data-schema-validator.ts
=> [internal] add schema validation test

packages/tiptap-editor/web/src/commands/deleteNode.ts
=> [tiptap]fix: deleteNode command for first node

e2e/cypress/support/commands.ts, packages/common/web/statics/schemas/content-state.schema.json
=> [validation-schema]fix: console errors

packages/tiptap-editor/web/src/consts.ts, packages/tiptap-extensions/web/src/unique-id.tsx
=> [tiptap] add polls plugin to unique id

packages/tiptap-editor/web/src/commands/deleteNode.ts
=> [tiptap]fix: mismatch transaction on deleteNode command

packages/plugin-social-polls/web/src/components/image-upload/ImageUpload.jsx, packages/plugin-social-polls/web/src/components/image-upload/image-upload.scss, packages/plugin-social-polls/web/src/components/poll-context/PollContext.jsx, packages/plugin-social-polls/web/src/tiptap/component.tsx, packages/plugin-social-polls/web/src/tiptap/tiptap.ts
=> [tiptap]fix: polls viewMode & editMode

packages/tiptap-editor/web/src/commands/deleteNode.ts, packages/tiptap-editor/web/src/commands/updateNodeById.ts
=> [tiptap]fix: get updated doc from tr in core commands

packages/tiptap-editor/web/src/commands/deleteNode.ts, packages/tiptap-editor/web/src/components/RicosTiptapEditor/RicosTiptapEditor.tsx
=> [tiptap]fix: set selection after delete node command

packages/tiptap-editor/web/src/commands/insertNode.ts
=> [tiptap]fix: set focus after insert node command

packages/tiptap-editor/web/src/components/RicosTiptapEditor/core-configs.ts, packages/tiptap-extensions/web/src/index.ts, packages/tiptap-extensions/web/src/trailingNode.ts
=> [tiptap] add trailing node extension

packages/common/web/src/draftDecorators/createJustificationFixDecorator.tsx
: duplicate links with justification on safari
=> [viewer]fix

CHANGELOG.md, packages/common/web/src/types/themeTypes.ts
=> [common] add: new types to RicosSettingsStyles

packages/tiptap-extensions/web/src/trailingNode.ts
=> [tiptap] fix: trailing node ext infinite loop

packages/ricos-content/web/src/normalization/normalizeInitialState.ts
=> [sound-cloud]: normelize sound-cloud type to video type

packages/ricos-modals/web/statics/styles/drawer.scss
=> Tiptap modals UI dialog
