rich-content-editor/src/Utils/simplePubsub.js
When `pubsub.update('componentData', data);` is called it mutates entity data and causes autosave related problems in blog.
=> Avoid mutating entity data

rich-content-editor/src/Components/InputWithLabel.js, rich-content-editor/src/Plugins/wix-draft-plugin-gallery/components/gallery-controls/gallery-image-settings.js, rich-content-editor/src/Plugins/wix-draft-plugin-image/toolbar/image-settings.js
Currently label is used as input id so input ids contain white spaces which makes them invalid. 
Also wasn't sure what naming convention to use.
=> Fix input ids

packages/editor/src/RichContentEditor/RichContentEditor.jsx
I need onFocus/onBlur props to be passed to the editor, went for just passing restProps through. Can add them explicitly if you want or use lodash/omit to filter them.
=> [rce] improve(props passing) Pass restProps to the underlying editor

packages/common/src/Base/createBasePlugin.jsx, packages/editor/src/RichContentEditor/Toolbars/createEditorToolbars.js
In configuration of InsertButtons, you can now exclude button from being added to `SideToolbar` or `FooterToolbar` by adding properties `addToFooterToolbar` `addToSideToolbar`, by default Buttons are added to both locations.
```
{
addToSideToolbar: false,
name: 'Emoji',
tooltipText: t(tooltipTextKey),
ButtonElement: InsertToolbarButton,
helpers,
t
}
```
**This is needed for emoji plugin**, because it doesn't make sense for it to be in a side toolbar.
=> add ability to exclude plugin button from side/footer toolbars

CHANGELOG.md, packages/plugin-link/src/LinkParseStrategy.js, packages/viewer/src/PluginsViewer.jsx
- [viewer] plugin rendering: redundant whitespaces removed
- [link] `LinkParseStrategy` omits parsed range if it matches an entity range (link duplicates issue)
fixes #165 
fixes #166
=> Fix link issues

CHANGELOG.md, examples/editor/src/App.jsx, examples/editor/src/Plugins.jsx
- closeModal function should re-enable default document behavior (re-enable scrolling) same as closeModal helper 
- when a modal opens it sets overflow to hidden , no need to validate document overflow , It was causing flyOut modals to jump up when opening
=> Editor example scrolling

CHANGELOG.md, packages/plugin-video/src/video-viewer.jsx
=> Vimeo - urls not prefixed with http[s] didn't work

packages/editor/package.json
wnpm-ci is currently a `dependency`.
It should be listed as a `devDependency`, so other people that list this package in their dependencies won't necessarily get it.
=> move wnpm-ci to be a devDependency

packages/common/src/Components/LinkPanel.jsx
I need to be able to use theme styles for Link Panel component's text input and I see that merged styles are not applied there. If there is no specific reason for that please let me add this.
=> fix theme styles in link panel

CHANGELOG.md, examples/main/src/Components/ContentStateEditor.jsx, packages/common/src/Utils/data-schema-validator.js, packages/common/src/index.js, packages/common/statics/content-state.schema.json, packages/plugin-button/statics/data-schema.json, packages/plugin-divider/statics/data-schema.json, packages/plugin-file-upload/statics/data-schema.json, packages/plugin-giphy/statics/data-schema.json, packages/plugin-html/statics/data-schema.json, packages/plugin-image/statics/data-schema.json, packages/plugin-link/statics/data-schema.json, packages/plugin-map/statics/data-schema.json, packages/plugin-sound-cloud/statics/data-schema.json, packages/plugin-video/statics/data-schema.json
- `plugins`
- some validation schemas refined
- `example/main`
- content state data validation now processes ranges and entity data, according  to the entity type
=> Main example json validation improved

packages/plugin-file-upload/src/file-upload-viewer.jsx
We want to be able to resolve file url on demand, this way we can handle private file downloading.
On file upload we will not save file url to content state, but some other metadata which will be used by url resolver to resolve it on demand (while also checking if user has necessary permissions)
=> [file upload plugin] allow for async file url resolution

CHANGELOG.md, packages/common/src/Components/ColorPicker/ColorPicker.jsx, packages/common/src/Components/ColorPicker/DefaultColorPicker.js, packages/plugin-text-color/src/toolbar/TextColorPanel.jsx
- `common`
- `color-picker` layout now rendered by a component consumer via the `children` prop
- `text-color`
- `color-picker` layout rendered by a `text-color-panel`
=> color picker layout render API

CHANGELOG.md, packages/common/statics/styles/global.scss, packages/editor/statics/styles/draft.scss, packages/editor/statics/styles/rich-content-editor.scss, packages/viewer/statics/rich-content-viewer.scss
Yoshi automatically runs all CSS through rtlcss and adjusts it for RTL layout. Since you guys already did a great job of supporting RTL in the RCE, we do not need to modify this CSS, so I added ignore directives.
=> Add rtlcss ignore directives

CHANGELOG.md, packages/plugin-mentions/src/MentionComponent.jsx
There is a bug on Android, when clicking on mention it selects the text of the mention and triggers Google 'Touch to Search' functionality and only when navigates to mentioned person profile. Happens when href is empty - added tabindex="0" so element is always focusable and doesn't trigger the 'Touch to Search'
https://developers.google.com/web/updates/2015/10/tap-to-search
=> Fix Google 'Touch to Search' trigger when clicking on mention 

CHANGELOG.md, packages/plugin-video/web/src/toolbar/videoSelectionInputModal.jsx
=> Uses unique file input id (to work with multiple instances of RCE)

CHANGELOG.md, examples/main/shared/editor/EditorPlugins.jsx
=> [plugin-link] fix: backslash in link panel breaks editor

CHANGELOG.md, examples/main/package.json, packages/plugin-line-spacing/web/package.json, packages/plugin-text-color/web/package.json, packages/wrapper/web/package.json
=> [react-modal] fix: mouse up event on overlay triggered the closing the modal

CHANGELOG.md, packages/common/web/statics/styles/general.rtlignore.scss, packages/plugin-html/web/src/HtmlComponent.jsx, packages/viewer/web/statics/rich-content-viewer.scss
rich-content: https://rich-content-maxSizePluginsEditorViewer.surge.sh/
rich-content-storybook: https://rich-content-storybook-maxSizePluginsEditorViewer.surge.sh/
=> [general] fix: max-width set to all plugins

packages/plugin-link-preview/web/src/toolbar/embedURLInputModal.jsx, packages/plugin-sound-cloud/web/src/toolbar/soundCloudURLInputModal.jsx
rich-content: https://rich-content-UrlInputModalCjs.surge.sh/
rich-content-storybook: https://rich-content-storybook-UrlInputModalCjs.surge.sh/
=> [editor] use cjs version of UrlInputModal

packages/plugin-link-preview/web/src/consts.js, packages/plugin-link-preview/web/src/lib/utils.js
rich-content: https://rich-content-cleanupLinkPreviewBlackList.surge.sh/
rich-content-storybook: https://rich-content-storybook-cleanupLinkPreviewBlackList.surge.sh/
=> [link-previw] internal: move link preview black list to wix wrapper

CHANGELOG.md, packages/wrapper/web/src/themeStrategy/ThemeGenerator.spec.ts, packages/wrapper/web/src/themeStrategy/ThemeGenerator.ts
rich-content: https://rich-content-wrapper-bm-fix.surge.sh/
rich-content-storybook: https://rich-content-storybook-wrapper-bm-fix.surge.sh/
=> [wrapper] BM palette will appear as default

CHANGELOG.md, packages/plugin-emoji/web/package.json
Packages that shrank:
viewer-with-wrapper: 524KB => 174KB
editor-with-emoji: 1111KB => 927KB
editor-with-basic-plugins: 1492KB => 1279KB
Please update the baseline file by running locally "npm run analyzeBundles" and push the changes.
=> [emoji] fix dependency version

CHANGELOG.md, packages/editor-common/web/src/Base/createBaseInsertPluginButton.jsx
=> [editor-common] fix:When a plugin is created,  the selection is on the plugin but you still have the curser in the text

packages/editor/web/src/RichContentEditor/handleBackspaceCommand.js, packages/plugin-headings/web/src/toolbar/HeadingButton.jsx, packages/plugin-link-preview/web/src/lib/utils.js, packages/plugin-vertical-embed/web/package.json
we shouldn't import directly draft-js no more since we're using @wix/draft-js
=> Remove draft js references

CHANGELOG.md, packages/plugin-button/web/src/defaults.js, packages/plugin-map/web/src/constants.js
Fixes 2 warnings of classnames not found:
- `checkbox_icon_unchecked`
- `labeled_toggle_track`
Example:
=> [ricos] fix JSS big warning in console

packages/editor-common/web/src/Components/Loader.jsx
Increase loader durations, so it's more inline with real world results of how long it takes to upload stuff.
=> Fake loader increase duration

packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
- `editor`
- `onChange` and BI callbacks get the up to date editor state
=> [editor] refactor(RichContentEditor) set/getEditorState concurrency

CHANGELOG.md, packages/editor/web/statics/styles/rich-content-editor-alignment.rtlignore.scss, packages/viewer/web/statics/rich-content-viewer-alignment.rtlignore.scss, packages/viewer/web/statics/rich-content-viewer-rtl.rtlignore.scss
Added rtl:ignore comments before the whole rule, because otherwise yoshi still creates `[dir=ltr] .class` and `[dir=rtl] .class` versions of the class, which we don't want.
=> add rtl:ignore before selectors

CHANGELOG.md, docs/docs/ricos/ricos-api.mdx, examples/storybook/stories/Components/EditorWrapper.js, packages/ricos-common/web/src/RicosEngine.tsx, packages/ricos-common/web/src/RicosTypes.ts, packages/ricos-common/web/src/themeStrategy/themeStrategy.spec.ts, packages/ricos-common/web/src/themeStrategy/themeStrategy.ts
Theme fix for multiple instances of RicosEditor / RicosViewer
New field for `theme` prop: `parentClass`
=> [ricos] fix(themeStrategy): external parent class

CHANGELOG.md, packages/editor-common/web/src/Utils/getModalStyles.js, packages/ricos-editor/web/src/modals/EditorModalProvider.tsx
This is a modification for #1378 to avoid possible side-effects for RCE consumers, and to apply the change only for RicosEditor.
=> [ricos] fix(theme): modal on mobile

packages/plugin-file-upload/web/src/file-upload-component.jsx, packages/ricos-editor/web/src/utils/hasActiveUploads.spec.ts, packages/ricos-editor/web/src/utils/hasActiveUploads.ts
Recent changes to file plugin made the `name` property not relevant anymore for indicating that an upload is in progress. Now `tempData` is used for this purpose instead, following video plugin's pattern.
=> [file] fix(componentData): tempData is used to indicate upload in progress

CHANGELOG.md, packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
- `editor`
- RichContentEditor: draft `handleBeforeInput` params passed to `props.handleBeforeInput`
=> handleBeforeInput params

CHANGELOG.md, packages/preview/web/src/Components/default-transformation.js, packages/preview/web/src/ContentStateAnalyzer/ContentStateMetadata.js, packages/preview/web/statics/styles/read-more.scss, packages/preview/web/statics/styles/see-full-post.scss
Fixed 2 issues:
- Edge case of 1 image + x plugins -> prevented displaying readMore (screenshot attached)
- readMore style - font style matching for both top & bottom scenarios
|Before|After|
|--|--|
|![Screen Shot 2020-08-30 at 12 41 27](https://user-images.githubusercontent.com/22775305/91656081-63f66780-eabe-11ea-8a79-bebd38810810.png)|![Screen Shot 2020-08-30 at 12 41 39](https://user-images.githubusercontent.com/22775305/91656102-9f913180-eabe-11ea-9b99-e9e3444b6d9c.png)|
=> [preview] fix(readMore): display edge case

CHANGELOG.md, packages/editor-common/web/src/Components/InlineToolbarButton.jsx, packages/editor-common/web/statics/styles/inline-toolbar-button.scss, packages/ricos-theme/web/src/themes/editor-common.ts
Fixed inline toolbar styles - for Ricos only
|Before|After|
|------|-----|
|![before](https://user-images.githubusercontent.com/22775305/92747030-74df8c80-f38c-11ea-9db8-9afbd1ab969a.gif)|![after](https://user-images.githubusercontent.com/22775305/92747043-79a44080-f38c-11ea-9e3e-64f20bedcb50.gif)|
=> [ricos-editor] fix(theme): inlineToolbarButtons new design

docs/package.json
Fixes sass-loader issue
```
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
- options has an unknown property 'id'. These properties are valid:
object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
```
Uses patch version suggested here, should update version once PR is merged
https://github.com/rlamana/docusaurus-plugin-sass/pull/5
=> [docs] fix(docusaurus-plugin-sass): update version to patch

CHANGELOG.md, packages/preview/web/src/Components/default-transformation.ts, packages/preview/web/src/ContentStateAnalyzer/ContentStateMetadata.ts, packages/preview/web/src/types.ts
Fixes:
- decorative plugins caused unnecessary readMore display (links etc)
- collapsed gallery is responsive to screen (2-4 images). for +4 images, 2x2 grid will remain
****
|Before|After|
|------|-----|
|![Screen Shot 2020-09-20 at 22 01 32](https://user-images.githubusercontent.com/22775305/93719743-2f417180-fb8d-11ea-99aa-5ce19cd91293.png)|![Screen Shot 2020-09-20 at 22 01 41](https://user-images.githubusercontent.com/22775305/93719746-323c6200-fb8d-11ea-9561-94bffcebb42d.png)|
|Before|After|
|------|-----|
|![Screen Shot 2020-09-20 at 22 00 33](https://user-images.githubusercontent.com/22775305/93719758-46805f00-fb8d-11ea-8c3d-f23f97916d38.png)|![Screen Shot 2020-09-20 at 22 00 44](https://user-images.githubusercontent.com/22775305/93719777-6c0d6880-fb8d-11ea-9db6-a1ceb291d6d4.png)|
=> [preview] fix readMore cases

packages/editor/web/src/RichContentEditor/Toolbars/SideToolbar/PluginMenuPluginsSection.js
pass `undefined` to closePluginMenu in mobile, instead of passing boolean value which lead throwing an error: closePluginMenu is not a function.
=> [editor] fix: closePluginMenu is not a function in mobile

CHANGELOG.md, packages/ricos-editor/web/src/RicosEditor.tsx
Currently, when using inner-rce with plugins with modals from the inline toolbar, the plugins don't work.
This is due to race condition of setState of `RicosEditor` from `setStaticToolbar` function.
This PR avoids setState when not needed, it first checks that ref has changed and then update the `StaticToolbar` which fixes the bug.
=> [ricos-editor] fix: plugins with modal in inline toolbar didn't work

CHANGELOG.md, packages/plugin-accordion/web/src/accordion-component.jsx
Added `onFocus` to AccordionComponent to fix a problem of draft, that throws "getIn" error.
=> [accordion] fix: add stopPropagation, to prevent draft from throwing getIn error.

CHANGELOG.md, examples/main/config/webpack.dev.js
This PR fixes the TypeError: merge is not a function in webpack.
=> [webpack] fix: merge is not a function

CHANGELOG.md, e2e/tests/__snapshots__/text.e2e.js.snap, e2e/tests/text.e2e.js, packages/viewer/web/src/utils/convertContentState.tsx, packages/viewer/web/statics/rich-content-viewer.scss
Bug fix for justify in Safari/Firefox has moved to `span` element in `convertContentState`.
=> [viewer] move justify fix for safari/firefox to span child

CHANGELOG.md, packages/editor/web/src/RichContentEditor/RichContentEditor.tsx
In Mobile, using **Android** device & **Google** keyboard, when moving between Inner-rce's, the focus bumps to the previous editor that was focused, there are two `onFocus` actions that are been triggered because of Draft-js & Android event handlers bugs.
In order to fix it, when `onBlur` triggers (of the first Editor that is been blurred), setting the SelectionState to have `hasFocus` = false, disables the second unwanted `onFocus` actions from triggering.
This change will only happen when blurring from Inner-RCE and EditorState is in CompositionMode.
=> [editor] fix: switching focus between inner-rce's in composition mode (Draft-js & Android with Google keyboard issues)

CHANGELOG.md, packages/editor-common/web/src/Utils/getModalStyles.ts, packages/editor/web/src/RichContentEditor/createPlugins.ts
Add missing types in `createPlugins` and `getModalStyles`.
=> [editor, editor-common] fix: add types annotations

CHANGELOG.md, packages/editor/web/src/RichContentEditor/RichContentEditor.tsx
For OneApp,
When they pass us new editorState, and the editor is not focused, the `onChange` doesn't fire, the ref has dated content, and when consumer will use `getContent` & `getContentPromise`, dated content will return.
=> [editor] fix: call updateEditorState when new editorState is given

CHANGELOG.md, packages/editor/web/lib/editorStateConversion.ts
This fix comes from Standalone, which uses RichContentEditor with onChange and update editorState with inner-rce contentState undefined (in initialization of table/accordion).
=> [editor] fix: convertToRaw when inner-rce contentState is undefined

packages/plugin-commons/web/src/Components/ColorPicker/CustomColorPickerDialog.jsx
=> [color-picker] fix: support non-colors colors in add new color modal

CHANGELOG.md, packages/editor/web/src/RichContentEditor/RichContentEditor.tsx, packages/ricos-editor/web/src/RicosEditor.spec.tsx, packages/ricos-editor/web/src/RicosEditor.tsx, packages/ricos-viewer/web/src/RicosViewer.tsx, packages/viewer/web/src/RichContentViewer.tsx
Atm, `localeStrategy` deliberately remounts `RCE` & `RCV` in order to compensate the current inability to update `localeResource` on runtime (due to design).
As a result, `onViewerLoaded` and `onOpenEditorSuccess` cannot exist within `componentDidMount` of `RCV` & `RCE`, as these are triggered more than once because of the remount.
Therefore in this PR these callbacks are temporarily moved to `RicosEditor` and `RicosViewer`, to ensure they're triggered only once
We should consider replacing the current remount mechanism with Context / something equivalent, as these callbacks should exist within legacy components.
=> [ricos + legacy] fix(callbacks): onLoad events double trigger

CHANGELOG.md, packages/plugin-link/web/src/LinkViewer.jsx, packages/plugin-link/web/statics/link-viewer.scss
- event.stopPropagation() when clicking on anchor in Editor.
- set cursor: text when hovering over link in Editor.
=> [link] fix anchors href bug in editor, and set cursor: text in editor

CHANGELOG.md, packages/editor/web/src/RichContentEditor/RichContentEditor.tsx, packages/viewer/web/src/RichContentViewer.tsx
once image plugin consumed context, re-render happens which effected the editor state behavior in example app
Fix according to react context caveats -  https://reactjs.org/docs/context.html#caveats
=> fix(editor/viewer): context re-render issue

packages/plugin-commons/web/src/Base/toolbars/createAtomicPluginToolbar.jsx
=> [social-embed]fix: remove link settings button from embed inline toolbar

CHANGELOG.md, packages/plugin-image/web/src/image-viewer.tsx
Issue: When pasting files in BM, image data url not used.
Solution: This PR just change the order of using data url when exists on image-viewer props, and use it in a flow now exist (uploading files not via the Media Manager UI in BM)
=> [image] use image data url when handleFileSelection is used (BM flow)

packages/plugin-image/web/src/image-viewer.tsx, packages/ricos-content/web/src/imageUtils.ts, packages/ricos-content/web/src/index.ts
In some cases Ricos viewer crashes (along with the rest of the app) when image source in image plugin is undefined. Rest of the code has checks for that, but `isPNG` regex match does not.
Added conditional check to avoid that
Yes, it is a one symbol PR :) After this check regex function get `undefined`, and returns false. It is correct, since `undefined` is definitely not a PNG. Why `src` is undefined there is another question, but in any case, it should not crash here.
=> [plugin-image] Avoid exception when image src missing

packages/editor/web/src/RichContentEditor/RichContentEditor.tsx, packages/editor/web/statics/styles/inline-toolbar.rtlignore.scss, packages/plugin-commons/web/statics/styles/plugin-toolbar.scss
=> [editor] fix: toolbar shortcuts - focus on first button and show outline

README.md, website/docs/ricos/quick-start.mdx
Quick start was missing the wix-rich-content-plugin-commons css importing, which resulted in every new consumer to ask as where did he go wrong :)
=> [docs] adding wix-rich-content-plugin-commons css to readme & quickstart

CHANGELOG.md, packages/common/web/src/draftDecorators/createJustificationFixDecorator.tsx, packages/ricos-content/web/src/converters/draft/toDraft/decorationParsers.ts
=> [*] remove string.matchAll to work in safari 12 
